---
jenkins_slave_home: "{{ ansible_facts.user_dir }}"
jenkins_slave_username: "{{ ansible_user }}"
jenkins_slave_group: "{{ ansible_user_gid }}"
jenkins_slave_servername: "{{ jenkins_hostname | default('') }}"
# content of {{ jenkins_master_home}}/id_ssh_rsa.pub
jenkins_slave_ssh_pub: ~
jenkins_slave_pkgs:
  - sudo
  - facter
  - eatmydata
  - jenkins-debian-glue
  - jenkins-debian-glue-buildenv
  - ubuntu-archive-keyring
  - zstd
jenkins_slave_pkgs_extra:
  - vim
  - tmux
  - zsh
jenkins_slave_distris:
  - trixie
