---
common_kamailio_deb_jenkins_repo: https://github.com/sipwise/kamailio-deb-jenkins.git
common_sshkeys:
  - https://github.com/linuxmaniac.keys
common_ssh_users:
  - "{{ ansible_user }}"
common_fail2ban_custom_template: "jail.local.j2"
common_pkgs:
  - nftables
  - lnav
  - acl
