jenkins_master_hostname: ENC[AES256_GCM,data:Y2Pm8qG/4+svRHH4p9/njnHc2CxvmKA=,iv:Y7vtTZFhWrfj5dPpqiJOyBcnC5FqJ+ZqGXmh00SSJa8=,tag:4haPPmjKtBONz0/MSxdSYw==,type:str]
jenkins_master_admin_password: ENC[AES256_GCM,data:kUjoeZrOJByLF3XipmA6njZ1WhE=,iv:4ZzQGJ4DMBYqjBHxXBqK5fYd8WV3JXvyA9UUnMczpRE=,tag:6aszaZeGr40WKYrhzWczWQ==,type:str]
jenkins_master_kamailio_keyid: ENC[AES256_GCM,data:HY/suPp3wgg11lYLgqsV9SD+3pK2QH4sM5bTjbSSdj2V/NuS6ca9zg==,iv:z6BJDgCtDikGd7GDvWHOWZLfCSMbKwDomIyxayZ3st4=,tag:nkNn5pO4eAroVjMxFtnCZw==,type:str]
sops:
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YWhYQ1pQbTNrVWZIejF1
            TDRUMGR5d3pmbHhIcHRQUXh1VU9VT2Fab3pFCmNtS0dDM1B3eEcveFlyQnQ2WXlT
            RTVYWDRXQ1hvQWdBN3lEYThNdlhvMHcKLS0tIHA1UVp1Mm9SeEhIdi80ZHFYL1FB
            UnBDbklFRzgrMzAzVHIwRnhOSERwa2cKHri4IaGzn2MClG1LbLCekBCQ/PMfjL7U
            eLagye4iLr94G6K6r1xX2XIgBwA5rg79E9lbz98a6T/etmKd8zUL/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-20T10:27:32Z"
    mac: ENC[AES256_GCM,data:LBjFXuHw10CtF+m/Iuq7lYU4d3cSanGcZno4iN3v+i5w2cdnjOdNjm8zN8YUUfpmTu8JmvE58/S496T+qi0TSXqW7etwIRaLwqMVVDGfR2RzTm/wiGWJ4oYLQpAim4mAdJ+BGmynv6+qwxUkPfrUbcP4mEMxOTSD4eJ9Xjnppi4=,iv:lRhrie45b48oWnDlkRy6IRPjZQPCPm74ntfIJSyM8vQ=,tag:qrtylmZkqttBzkEqdUlnIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
