jenkins_master_servername: ENC[AES256_GCM,data:ttZ5CvWEQNr2+rL3PzsqSneBjb23I8E=,iv:woPMNHhyeGKCz4ST4QqwJsWR9yyR+ilaD9hRl+v6UGc=,tag:eqbnai0vwbP5Orzg2slDPw==,type:str]
jenkins_slave_servername: ENC[AES256_GCM,data:yUSmsL18NF97ogKXN/TWsx1spViuWuUeWZdU6PL1vg==,iv:P5CXeZmsj1Z1RREJN4IeAqErp/4YrXXfpGTMacHMqEQ=,tag:G7emjStCMxKVlbn3sZGkEw==,type:str]
jenkins_master_admin_password: ENC[AES256_GCM,data:pigy3CCJSUzc3aAgsuIfO8+tZeI=,iv:Z8xtK0ZX+4dvzfwxzgW4SO+BGtybyNKQUH+kfsfjaUM=,tag:QxXaqMjCMj3Wd0oScZ5v+w==,type:str]
jenkins_master_kamailio_keyid: ENC[AES256_GCM,data:X4cSblKBcHBgugjAzZU5P7GlRSJEj1T7DLgmuNlkM9BceIxK01omyg==,iv:JD4j2j0kfilvxXiJXsL5ILQxFQa8FfeXNw5izFDigCI=,tag:OEQd4eyPYokYxbZ8PMjIqg==,type:str]
sops:
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVjlPZ09lMWVVaEdSZFpP
            OVBhQVUwWEs4a0dOL3hnRmdrOXBwOWw4OEd3ClcxVDJ5bUw2enE2bXZ4THlacC9a
            VmRtVCs2UFBKWStSdkRnUyt3d0dtVlkKLS0tIFdyUUxBK2FwdU45VW42cURUWXBR
            ajIvYW94WFdoRFlwV0F2Z3p3RmF6aEkK6bQa9LPmE8PRk/c+15oX4VxOs4rfsGlJ
            GAsxA4C0+JwBPd/KamEOKKVtPrRQveZhWlnCQavJsz1hgsCFpBuJbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T10:12:23Z"
    mac: ENC[AES256_GCM,data:c1nWVk2d0YVDBsgYo5jan9JhITDS3g7gIKbAXcVYgISkJvhSKWlpBxNcQPz1Df7g4Kj1wUvBhfMHVWnzkFRhyXBQ/+375VVGXmoTfbXlXVBSThQDaHqofiWk5Ur16Bf/99C65vjWcoUDMMetFoXJ2KaGFiUJe4H1Y++BG3WDt0s=,iv:1XQptTqOjFWSUb5J4QYehqXTDgcYqTEzinWRQJatdiw=,tag:GcmlLHOYOeEwTIhst2buww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
