---
jenkins_slave_ssh_pub: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkK0sLqtQXto/6lmFLv3oZbnjl3zB3MwyKYLIAr9fOavsrykrPhMqTZ8BK/EJ+/Jphay/7GH8yUPBVwuaaSbIkgJ8PrZNbh/78BRM+lndqr21qoEvimOC4hhr9r/1kxvVn8PjDqnMFE5yO0rFF3TEHfaSNY/60erb8x1z5DBDwU0LpWW8ukNCPGWtwkzDE2q+0yEch+6DQHc70dRXbPYCCAUqQ8FcDoMUVlRq4mtO52OckBajokZhdFodTKhOjD9soyFwztrEqC9EOuEJunPiDKSdiEsmuVLM7hx7t3pP30FfBh7kLN9eluXQem7VEIXhbzC9sij9hPueTRVFHBI776XS4knm9RNelhpu0CWMKfblUYJv8eben87eOTJJo7qjfmTz+Jt07N6ur0or2/0lQJ/I8KC+DBYr5QFQa8pTEC3qIK+HkoUW+9RRuQZK6SzCnsA3u4quI9YCND0WDJKivdLG3hyZozTbOfhSzmvIzx6Kul889YuBwxSyQhCHAzXoykPuv+qnCEMu/H5EN9uyHQCYsqNU9w9ruqdtQAs/rUtQM51S+X9z0Z4XdOXHwiPr3lrH9KWpWnKu89rnobGSO8bTu7X6DmQDwbd0DShqfpX18AEYlXXRRTvbDIMXFafmvAB8pLCh0iLeKnw6Baj1X+O2dUcd9/nQKuuy3/Y5fZw==
jenkins_slave_distris:
  - bionic
  - bookworm
  - bullseye
  - focal
  - jammy
  - noble
  - trixie
  - trusty
  - xenial
