---
jenkins_master_admin_address: "<jenkins-dev@kamailio.org>"
jenkins_master_smtp_port: 587
jenkins_master_smtp_reply_address: no-reply@jenkins.kamailio.org
jenkins_master_smtp_tls: true
jenkins_master_executors: 5
jenkins_master_plugins_extra:
  - name: workflow-aggregator
  - name: git
  - name: copyartifact
  - name: parameterized-trigger
  - name: build-name-setter
  - name: email-ext
  - name: timestamper
jenkins_master_environment: development
jenkins_master_ec2_region: eu-central-1
jenkins_master_ec2_ami:
  - architecture: amd64
    type: t3.large
    id: ami-0b1b3a09797273dce
  - architecture: arm64
    type: m6g.large
    id: ami-08e30a6ecc3b981fb
jenkins_master_ec2_name: "ec2-{{ jenkins_master_environment }}"
jenkins_master_ec2_security_group: jenkins_slave_development
jenkins_master_ec2_subnet_id: subnet-005bc72e8c7433d27
jenkins_master_ec2_ami_distributions: "{{ ec2_ami_distributions }}"
jenkins_master_allow_anonymous_read: false
## This configs depends on jenkins-jobs repository values
jenkins_master_scriptapproval_approvedscripthashes:
  - "SHA512:00564656b6a24386b1f3ef30fa4060f8fbc8cdb8e419385972d1b5469618e13765f33c6c1bff87063cc8ceebc556143ef59f743af91bfab239b2c82fa774db03"
  - "SHA512:014091a13aece56229e52c76a939e5432256acdb0e9b2344fcc8ec7ef488afd34288cf7e25cfe5cdb55f81c25b2e7e9d229e293e68a8c3928ea0bd5e9ce446d9"
  - "SHA512:015bf2044da2e312ce8ee5c965e4227ebce5c2e8248ee79481956f06503cde8ef05768fc72e4580ef29e1266c9257b76d6b1155d6f1605555f85b3be5a69478a"
  - "SHA512:03bc04c94fd3f926a5dcf814b5d2c3b07c0dcfb990ddfd9513d1442dfdd38b3b458be598571ec888b8f8b9cf31b8199c35e393cba613b13b7f74e0b08209535e"
  - "SHA512:04137b872593ca29d53891aa04d7a521246de2e0c686ed67ccfd0efa634746e8a216f28ad527e7056ab554184bdd7d3df03f764f81ac73d9615b49d3e73b78dc"
  - "SHA512:07bdb1487ae4aa77a6c5068d98427fc107e545a5f0e7d27a2e64ba26a1c7d1ab324c7804ab80ad9c832f213dc5a8eebe7f8e9f3ffaf2983ed433de41f13ee477"
  - "SHA512:09074289f6181deb44e53d904c33081ce0aaf69e6cdc9304d732829d9a3609befe5c97194be3a2ab9a18006399e60507e42b2e9bcbb8d334940d9d05c40d821e"
  - "SHA512:098913b28b44a40cbefd8fbe7bfd98413a7b407d65b7c9599646b2c6dc7b5b2e46884195c9fd2be49c1103e0f4b1a5555d7c4c15bd4d87a59d6f6bd8c1da9dab"
  - "SHA512:0a5294c306bcb964a5e7bf654ccfa898afc5d22f44a31578fa3cdec684cff40086c726843a2f385b5a7dc17bd943646c1d3914147f21bf7c19b0160aadacd8ad"
  - "SHA512:0d5f0d245839e9bc6995b1525e877858dd22424ada4acd0fcf79af49eac2d7beacbe7aae7749036f352fa4bb9f6afa8f5556b6c50d22b587ef4094cce1c65bfd"
  - "SHA512:0f630a12ba36d6b73ad2d2d993f1827492eea9cf20a728d605c9f3c65120ba13da46d0c4014b2a63069fba83cf82141f578b8aa1dda5e0c97249a5b77da30cfc"
  - "SHA512:11de8bbc41f338a9035db0fb7b27e935ef158cbfc7c81033efa7f36ced1b499eca54874c710503713baad2650ce25b4f3e28c1c5c8327579f510967535bb036f"
  - "SHA512:1c31b9fb5504196b5b20fc468c5829c668d196f39d34bf8c2bd866a371554de5ebb8551eb04db3442fc919c149442b2b77d43383e674091ceeb5f26529a24f73"
  - "SHA512:1cb021c1e2f00dfdbfb70562292dd77d8783d3faa40f9e21e3217650e5ce7bfa14d069494dfe66f82b7d04e46187f3725c7dcc7408b2aea734edabc6a710934e"
  - "SHA512:22d5de0732c0421ef306fd44c341368d48c1d54bb618f7482d87e1cec2533713f7c560fc9f1a91e2f8ebbc57666cd1f239eb5f48fb889299c9ccbf81a2a1097a"
  - "SHA512:24718a378be9e320f436eb71bada1084e8a2fbeb6f6c46c4e4c764952c0f54c69dc89bc2cc06d93e09c65bf5e63188d5de92c3c46edfc1ccdae27d60f4abfe49"
  - "SHA512:27b29c585e5dcfb43d2469bf65e588b1fbfbd5ed63775f8ace3681b808cda058a1da0978b427e8d4ae8eb93464021634b3b4a1051d7f8ddf9146b4c56255e7e6"
  - "SHA512:2c3506ee075858fdaf61b1f3aa5cee5e92327c3c3265e9526365c909be3451bf21a1b8745e668dac33435643a005f1e133aeaf429965302f2b91727b114913b1"
  - "SHA512:2de6a8e85864ae068b138d68cf29e635a1f2e82dea81f932612a0060b05666c9b7066e2dea24f1fff9f771f330a193a0565f2cbf6ac773359e669201d0dfed6e"
  - "SHA512:3221c680ba29019b480c19ea56450bf00586c67abfc9aac84be35dfab56adbcc57c7dc14d19ae01a51f27fc291c88d91a7af2c06cf5b9d2e7764b0bca7705363"
  - "SHA512:3812bc815d388a0e548431d63d67ac62f19a40ebddcd98f0b1d06a97041543651614b50a24a5bc42a81bea13c33cf09ada27954e3a026ce063da3433d1c28510"
  - "SHA512:3815598ab5843511d11c8e072f26a2bab54745fb9738104410c1b5edb634279d1824fd31aef8db89831d4bdbe0933682b4cc9403d9af163ef43ddb01fe7ed354"
  - "SHA512:3ef19981007e57dceb6375405e15e8b5b217950dfe6b6404756bff159e94c66973992cf0866a8f7020e7d4a48947bb168673bd48e3d3da67dc4a18fb7cde82a4"
  - "SHA512:3fd049f2808be4a31165de34302b5505b63f4615446fe7813a05837c26d81ded18668e9a04f75273aa9aaecad61661a8cddfeedd07da143451ded985d3b8339e"
  - "SHA512:41ebaa9f51b6c77abb61f8a658d8b0f66fd08d7308a1f40f0f219d1dec8f4e5ec2a235175531e34f4fbe9784d1d1699694c8b184778bf503c47ae4d15711b881"
  - "SHA512:44d4d59f7922772c9d78159ce2b374e179423810aa595af7e121dafde1c1319dbd064c87a30ea75bf40774e96889152efc4f2cfbbbcc438af420a05bbfcf4ca1"
  - "SHA512:463a9e9339b7690d0c42e02f7e9e8655669f819c439ee0c52a9381126fa8f9376a9dd195ce5ec4f2a02fb3e250a19bd9f9d36f156a0444d2f82bf5740daa101d"
  - "SHA512:494c026fd19b0e7eb776d352f27198462e6679f6d397291abdb29f6787afcab48cedaed576c1f088cde7c703191d3605efb8acbb61164c7c2811f6bf6a79381a"
  - "SHA512:4b2c18b4639d402aea6499cfc4b8e08d6425697e7db86b81aa6d4dc3a96d542019b860741913ee74348331a7840d98a0d436891378e06a57841e2f89f9ead2e4"
  - "SHA512:4c3be15edc3acc7cb6e16f923a5822a5646adf4967e910fe3c822984775124f84b04f06151468a7ccc34f92739e246b9dbc205efcc53d88c1b9e52df162742a1"
  - "SHA512:4e0fbfd6e6c42ba8676c422b2805ff69a614d02a18b95fa84c5fe438ec1749868204c2cf4c393c4c0ddb384f972e3d0f266846394dc9eb2dacf944fa64dc3392"
  - "SHA512:4fa6381ef0d1188f04b92b651c0e57f34ee26c29cde5fa78f528db31aaf68df963b8fa5500e45df8c7c5e5303930ead6db11b95de608cf82703694cb9c3a126e"
  - "SHA512:5359a4eb2b5fff44e99e9f8f40360011bd3ee4ac04078d2f2a53057c6983b4efe684d1814653ebfebf8ceb140dae887d131b277ef4599e3bf834cc75225845e6"
  - "SHA512:56e8976f1f7e5f5753083c0430ef98c0bfb708df9cd79260284f7e1bb8b8e2231cd74e85ec1b379dc4d5362f2c8b1f8ca413da95308a16785c11123d0660c264"
  - "SHA512:56f6b78ebdf8c41a67a92d947c6e92972b5b0dcf3788a74c4937d1fd7d2982b0d992c0d24ba43772fbd246ad6f7f611ef0c38535288b2d83c28ac13cc448bec7"
  - "SHA512:58d5b1ad5d12c8549012ba322eb645a43d71bfb2f1980ae1c52fb167796f5c50d4549e5339458ada591a082bf3ad0501ec9d22c4b20238dd5523b5497c0fd697"
  - "SHA512:5930c4cf4361b0c0263899b7e4ef9285f30b91b48853854a998ba0f2bd7725280cdd76d1ebe2a00ee091fb4d6a2a9d250bd5b8853effbe4fcc984283fd0c0440"
  - "SHA512:598f10e2db5ddd3f12939d075c0b3e5271c100706a27a4447b9ef72261a62e81d6cae4270d306d779652dfc7489dacf7cb6cd1790ec4c99b384af5937387429d"
  - "SHA512:5bb76461b79bfaaa2b046e1137374565e12b5d1308e1e71f9e8c0bd3f292854eb8ed9e1d56da4ca127a0f8c79bb532849ad730ea7a0515c068e383686c7476eb"
  - "SHA512:5c2dd60988b3cbbd829872e4774fb2c527baa199a0d6485c204fc56d7ee8709e2381dae4f983a343175fdbd86da0e61ac53cd41fd1e913acaae057b69302ba9b"
  - "SHA512:5de604f4ff8b56f398d0ae814eb84418d57b76f5c51388d15e645181a566fe4157352812d2f8bd04af7e8ef13e79c0100b61976216d50796f05b472c2c4490cf"
  - "SHA512:67d12f188cc650817dcdd57bb20684b4656307435ebf86b4a6f8aec40fa0e847329392231075c9586189e23da37e150a29ef8845fda6be9f64ec0cdcb70b6a43"
  - "SHA512:6a41326fa8e6b85378bbc7c2447e1a25855059740495cdd5c48cb3a39cdd36ba336da1c9c0820d5cea46b6113a4ecdd0969cad82c7a9c8fc59a6501d1727c77f"
  - "SHA512:706b662ff0d4f741a28bd758f13bf139e97984cbdccbf3cb3da657ea302e639c5eb5c421c722f651292cab4ba9400a31fe3cc7fabe60436b4dd71b37a7ba8e22"
  - "SHA512:73bee4edde2ab46b81122868587972eb6b092c07d7dec5a20b4b4071ec7aa7c95cf53ee0c81ba7d3f89c9237e8c0a0e157fded544ccad89be8cb36673e040845"
  - "SHA512:7668fbc7c69e5f0c0a68f2904a9d3ce52b83599529c674741ff092280198d096bd4d1f42668d81368e0718664686cb0e89debef2d97f5d0e35c138a52723bae8"
  - "SHA512:7ccae838924fb96ad86aec0f275d717d648e9acb379f4ae2f4c5e1302b8d27617ccedab92ce200607cd781403772bf710a3d9076c20e372d69cd9c1cd15873bb"
  - "SHA512:7e34cdf00b5904f8baebdd62ca5b4a2a2236de697bd955779f5b622a0cce586bdefd9dba6975db12cb27ba9e71c40992c3787bb366f13b5bcb5e5dd50357c823"
  - "SHA512:823f6476f9d3bfa601a0ad8c1a3c171e810be458fab569b16c057a842a8e1f5ebb6855cc80fe7222eff8cb6d67b56e411207ee1a828974fe97ed5dd80e3e24dc"
  - "SHA512:82db769bc484fba045cb0a3accfeba7a33cc1deb670b495139d77a38f90ca68f42d495064fa846b032ac0d96f3fb2d419c16e141aae761838c8ab4eb31e51729"
  - "SHA512:849ea0c59714dc5ee0d8b4a0a434f0c0c8ceafb0f674601d27ba2f873bf5a4c127e9a3321e1bbee6a03e375e2cd283b7dc182969444d3f5d43ef1e40e67d9a7d"
  - "SHA512:88c2b55eedb6e82cfa31ca46da4880d34a7d42ac729696c9c18f6948051ba62614175a977034deb8edaec0984489a9714f038c5de601a7773dea409ba0a88719"
  - "SHA512:928c435676afc59f21c05e326626d4f1a0cd55025330bfbcb6c74e0f5934a28d0511d0a4737f046c69088e8b446de9d9be0a1461807dc20af0bfb8f9bcc43bc6"
  - "SHA512:98b1a2e225f4ecf18bd13099c9bddfb51acf563523167213a847eace63cf4f5366d904934b9b30645a51a00e36d5fe44a50f8d3814f9a2f2059fbb7b38859886"
  - "SHA512:9a1dad6f410983ce85524e8b520ca88a735927f089ae8067164d5afbc4192962a4a0ecbc365344c6b5d57621526cf720aae9122fece6c9fbe1f8b92de46a63af"
  - "SHA512:9acb2a4dbb71c9d64756f2f9d5f5ab5b63c8019c541840086bff31a661e0df8b550bf37a932ae89fc9ac668b8d10a78736fab90639c24ff08d9f1173f2471b60"
  - "SHA512:a01f8f6c035b5525b77faeaac9abae0db502bc71315d21d9348c3bc2e8f0d6ec086cb0a882e8e46dd25160f8a0b736d8cad1afec5a5337939fb8923faffa3ebf"
  - "SHA512:a42cb0842e62e28b90a4c41911cc566c5cbaa0dc0bcb5f37ab95c3811816e3474e127760f750e095a1258f75fabd3a2b6c4040c75081c57782a0867d1253fa89"
  - "SHA512:a6298f3e5436d1bc974bf1f75f38669ed8aa2cf6d9a546af38a40f5106e35cbf4cdedd18dd9e4e05d9e77afd72e987c1fb05c8b6cda4db805a4df79c8e292f6f"
  - "SHA512:a94acdea71acff8d63c8c459458e1f14db5f9abc1082918b07b66e44603bb4e7c276b49053186395379f1b68f8525a19b76525838767e99ae4d342ec9635bc8c"
  - "SHA512:af309dc6ac58f5cecc16a71961f13ba1c944ac1aa45337aa0782c1d18beff8c70bd6d769894e2786572b159b177181afe7e27d08d648b5054a31ebc4d6d37273"
  - "SHA512:b0eaf2bdb3488b7ee12d68c039592443607b30bd6456e2b9f6b4c5662ba895066442fc351699c10021fa3fbd46f4006f716187b7b8815ee6f0df6cadd3962782"
  - "SHA512:b2e01d5272d8e06f4379bc1dbdbacea6d6129ea8956cf19f2926daa5b5a90413e05e480d74bef9b1e0e53295e5112d87a8bc92d0d8ff9f482730e9b628beb0d4"
  - "SHA512:b5e3e2677d316b3c92450c11f0615f57af166ce0ca09837e1eaf968a0980e3dac7b0c49f86f2b4c752473308697306027925fb5a8fdc7dfc0299e15540817e8a"
  - "SHA512:b9553114e9eff20ec0f5d0efd14efb41a7d15b8a38b5f1da33caf31a4e5b2f607315f733a92a40258e3e96a95d9a43e77deb54a24194dbd738b35356833fe4e5"
  - "SHA512:bc2022bd06669adc6d9fc8ddcb0de8d7a19d3346e4db4ddd61b5543b34ff6558061f368bcd20902de92acf2f9785897f216d06eb3b1e7266efe120f252da3273"
  - "SHA512:bccea872f337bcd92fd9dc9c363454ed475f5cb72ce20014cc99d5cb56d4e7a6dc89606069058c0804cb47ddcddb004f6480a2f7c841cef8d39a30607c6420a9"
  - "SHA512:be1678a344ac6df7b31472cafcc678b456c92c11ed6be73cae1384bff86d703b356ac2379497b68c6f24ff3d2f3c3ba2dd3fd512d403e8547fc103c0d550a94c"
  - "SHA512:bee581bb9173d9fa2d47c9e623aef7c17ba6b2d816f800fbecf57d25d1664f0d8d7ebef402e143e9a6564d79f5cb26ebdb11e0ebb8fdd573f50f276f8b6fe36c"
  - "SHA512:c766138ed30f90f80ba7a8dff4dd264d90e6b70533933e32b5b933624a79f2451affea2471262fec05101a3460cd0ace54bc431e96edd243f85d27fbc50850c8"
  - "SHA512:ca2741b78ca5f2eb839f6b35ce714c386912096345efcc7bbbde42d4e86770771c93715c8f12388ade6352dc9502ae17341d4b5ada4c9ddf49b7d3069fe4f183"
  - "SHA512:cb9a769f7d47c986bf37992fdfde3a48466d53fa6e2b2b4431e87898e5f27d1da223da88074d5a12cbc08a4f192019be8d9f2327e4c5ff498b3efc8306bf260d"
  - "SHA512:cf7a212bd207afd6111402c39063511ff6a25f5b9c7ac31a0129f629d0be9df966c916bc336fb01303c67c2250830e6e394031ae3804c9fcba2004ca3b563dc4"
  - "SHA512:d0d4281ac65ffd992dd50fa562f49742cc6955ab21bb0bdab857674c84efbed07b424b2c5138e18dc6069df4d40c6471d177cfbf1f4567c7430a7aa0c8f6c004"
  - "SHA512:d13f8cac4e69cd6f46864986fef0723e7f2867500fe72c28a66e8742f3595fd8d6988d2bd83e0ad9122bba35960ead5b09b92c2fc5a830c140957b0ba08c9956"
  - "SHA512:d46d64010e0d9e4e0a18a951277086ac381edca3717da266bfc76afb816d7400a50a7dfc841284c5de10e9b158dfae5f63de503af4e9d1ef6bb06de7579adad1"
  - "SHA512:d5fe5430e70be2f4a43eaa4e487ad05b241a368abc38fcf3792e1ffb575cd71a35137a79fd9d6600df9946b4cd47a3cc5cc62651b94bd1d523d352e3b486ba1f"
  - "SHA512:d81358644ec3ba76000bf0b6d581a5f5003fd956bae5c42f74ef31dd29613a9e846fc3404b3b5534dec5e54e96134a1e734cf442f6faa34d74faacc94dc1e5fc"
  - "SHA512:da3e28de513f07276353d324cfb9222386334b7897fbcc228fd5c956694c14e00c66f42cb98caaba0181c2f86e6e2d496246b58000d3e67087b7bb13ffcd2d1e"
  - "SHA512:dc56665b1d2992930dd3a4e7f3c4db4957ab41c3bb29f2fea90ea9272a0063380f5dcb23aa8e414048cf9c5ce1e278e0cf1c5f88ab792e77c46739f91b4c468b"
  - "SHA512:e4494ec7d92495b9b57f4a4ec9350d420097863d53c0ebba2c141c1b7849c9ee35a2c2a076ee381fd2bd4b24e6c75a5cf228ea01074157ba71e35f7dc0bf0845"
  - "SHA512:e8106bde2c2bdf907f76a6d2c5bb0f8e092edc9919badc166aba7901d0ad8d0f61b0feee05b2a81b37561af9ca246a71dd84bce3782a55bdcfe6053f2931ce22"
  - "SHA512:eee7bdad96477e058de52837431e9c279197a3a5992c8b9bd7c3251425a35761ec87f01f787af621b1aeba2df6c347e32b94f553da1dbca9b1e101ee98b1c7d2"
  - "SHA512:f1202a8d7fe894305ce3622cf974a5ed66e2688533afeb32d93feaf2c73595911a878b0ad7432dfb1d42819de22deacda89d34628ba4a9fdf309cd14127d0449"
  - "SHA512:f19806614626ea0a3b9a0812af72b691ad57578f143cab8b8571bdc2dd1d978c22fe0e49a5155fb0dbda54302a954917e4a9f6d0806a9774aa5066cbf067f2a5"
  - "SHA512:f1e67be0b8ba36522d1b2a69d41cdfc90c7d17a69e50d4cc69b65e47174c6d4c31200521e2149c2a111165e52a29894d693f1a3379f666952f9281a933deb18a"
  - "SHA512:f26962930668613f89ddfca25d228878515d6d4cfc98d904bc47023a8536b40ba247cab7c53948063e3627e97f851ca458bd489092f08f09bfa767d439c62cc0"
  - "SHA512:f9e856052086fd042ab68a20f36336c7bc3199b285b51fd1289e07d638aec4046d2a7795f8f13c36b2397188515ebbf6789abb3176dc15cf8945f7cd1ef9b02b"
  - "SHA512:fbea971020435289ba02632eb671b01ec36216cbac5cd5f49a513790c0cc1e3d31f657ad9333ca6fe3b480f611efe6b0cff5ce0e29b9d4bd3af45d1f8a974ba4"
  - "SHA512:fcc14e435fa460ec092bef43c95aca1ca3ed1c3cdef9747860983c1e96edacf457e82f81b8b24460f90586bb80c3f850448a27314f5ea1133b140324bc68e132"
jenkins_master_views:
  - name: kamailio57
    regex: kamailio57.*
  - name: kamailio58
    regex: kamailio58.*
  - name: kamailio60
    regex: kamailio60.*
  - name: kamailiodev
    regex: kamailiodev.*
  - name: kamcli
    regex: kamcli.*
  - name: rtpengine
    regex: rtpengine.*
jenkins_master_views_default: kamailiodev
