---
jenkins_slave_ssh_pub: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC08uuxDx2qtHckap9zDZG3Pcx64LSK72ZUGcG6v8/1Z6JQhyKD0wBcIWhGTgW5/oCgZOTspZ++j64YFedCRjVzK1BJQ8KET8mfIV8aliVuvtOYOF7xAPbX8qUya0SzFTr4rOUgsmcuesF6Qfbk7IjAmrcXX1xBdWDknSIFac4fxLuNVnrxTc9DlJZ0cxHtlKcIhX8tkmMrP5bc7Lu+jQtB9aJzGdYYRMAUJAYdXcHzvBMOATtizrpw13LNgyuNkZEyxmthPJZyMkGwmnEfKrZb2/V4QWw0krTqkfsHnGyu8TVQsrl+oXLXB4O8/bHwNYfkdcKzzozOyLAqV5lU68y9mVWPqAJAK2WBF663ErsxoCaIH0luWjQbli81acggggr7OZ24qaLsQsWv4LDMoZHBcN+JspmVFMpi0jjlXJEDq1ZKPiZCQyuHc3+0+9cj9nPsBbzths0zyRWugjxN23DS/hl3mAefUjEQ0OMsPrCwRdU9pGTojmYwSCivyuOy0/bFYr7KxoFzq48+hu/U7Ki8CQLGQv6mt/GTIGT8RT9BadC/dIlP01du5GpfCZamOtR/FT9iDYzADpiweA0+F555fqpQq2orrEYtjL5QpVoYulftIz64VS9Is+jf97xuqw8jrrLbcrGNRG+Zn6jwPcbboXYzqoTJwZdV/vUCXabZvQ==
jenkins_slave_distris:
  - bionic
  - bookworm
  - bullseye
  - focal
  - jammy
  - noble
  - trixie
  - trusty
  - xenial
