---
jenkins_master_admin_address: "<jenkins-dev@kamailio.org>"
jenkins_master_smtp_port: 587
jenkins_master_smtp_reply_address: no-reply@jenkins.kamailio.org
jenkins_master_smtp_tls: true
jenkins_master_executors: 5
jenkins_master_plugins_extra:
  - name: workflow-aggregator
  - name: git
  - name: copyartifact
  - name: parameterized-trigger
  - name: build-name-setter
  - name: email-ext
  - name: timestamper
jenkins_master_environment: development
jenkins_master_ec2_region: eu-central-1
jenkins_master_ec2_ami:
  - architecture: amd64
    type: t3.large
    id: ami-0b1b3a09797273dce
  - architecture: arm64
    type: m6g.large
    id: ami-03ddfeb0b4a5c49cf
jenkins_master_ec2_name: "ec2-{{ jenkins_master_environment }}"
jenkins_master_ec2_security_group: jenkins_slave_development
jenkins_master_ec2_subnet_id: subnet-005bc72e8c7433d27
jenkins_master_ec2_ami_distributions: "{{ ec2_ami_distributions }}"
jenkins_master_allow_anonymous_read: false
## This configs depends on jenkins-jobs repository values
jenkins_master_scriptapproval_approvedscripthashes:
  - "SHA512:06affa7671be385edb4d9de1acdf0cf608739eacfdf84222c916fbeb381946caebd4ad62dc023f61cbba4b7eb03bec010828144d8bb74d95f04388dac5140b10"
  - "SHA512:09a4e935000d7a71dfb2458ac9bd7163f362ac00e13d0c446ac54fa4d23e070eca83e08c24f8ec23fdefbe42ebd074db978899227e91ee348d01233e0bb8a42a"
  - "SHA512:0b000aea3f3a0aa58c2db09aac2f983e4ebc2120f5a446c428724cb6e4c392883e48c6e6881e8a4878ea1641184e99aa433a50aef0bc451a08d07e2ccf4efd98"
  - "SHA512:0ec616e9949d67a82aa27020958668d4b2bf89410ae2f6597d6c5729b6953820aac94beaa1233cdf31f4ccbe1e24932d037fab76394c9f27cd8915d957eacc96"
  - "SHA512:1d26f63f4eb384a946ebf5d50924a3758c803054989645e973710edb2752d13a1d7fc04ea954713990645f3ea3e1fbcb806c6b9a63324cf63ff54065aa553273"
  - "SHA512:2087d61377e677f62be4e79a8acfa70f5411657d2d0db571d7ea8fe99f9e33005304deac7517be1a43ce50275832c2f1883e8f28d9dc1ae0f2a6be55f6d5e3e1"
  - "SHA512:242f012bc60ad25cf03b2641f2515aa95dda4e06c113774d51326b1b21d6c40c15f85bd4806b463e7d1eefb92b0476926003fb77c59ae962257fad8c8a7fcaa9"
  - "SHA512:2a4295cd86adc09abba91ddb357306fde89f6ee58c9c909d793df1b5751290d7aeb7a4e06fb42f4c8fd513e03d17bdeed1b43434e375ce75edf542e77f9ac16e"
  - "SHA512:2c32b37c83bf5bd186c6d0b60e7321dacb98c4cdfd7167aa484eea9d22bd1ef4c5eeb95cc966959724a86b6b78e6be92af4f311041601349f048e396d8789ca5"
  - "SHA512:2d60228c9c0621133d5b387133e6fb521d1dde65cfdf9480835c38401225d0b97d1e634ea79aac42eff7d8e241b0d26ca11ccd50f22f818026c2149ad90d49ed"
  - "SHA512:35b1ce6d5fbdb3b555da4c8e34d7c299c432477d99d827c350a0607e066278f357d0707cabc90538386b5a191b6f18a2ea1be60d8b691a675ec0db93d80e15df"
  - "SHA512:389aa511f19d99873504e3da7afa196f13d9ffa44fa9e4c9a39ed7c613c829a430709f9fab5b736b1b49a7921500b3d741c552eced9e8e5e11866326b41c8b08"
  - "SHA512:3eb5b1a8993b1fc53834b77afc437c1dc4defdd432a23f8b34e14b909ae7cd4efb31ab014f29000cd38275f9b50040ac915978ea85c9b5a1ef2cc8fda5a5cc5a"
  - "SHA512:48441522d2b8177c9c22730fb276340bdaf8f6e9f7daa7767d15a6dc820e3ec6ff8b234972cc93ea559550ccc0940fa043848d76bbeaf561874ebbea3ff72744"
  - "SHA512:4a8ef6ff0b349f5163f046c95ea5e1714c3a0da1063836f922c1e62f261ca00d00fd2c35b67b55bc6c108b1535ba6e45e7b0cc17ffaf535aea9b5d57345a6cee"
  - "SHA512:5174affa4bbfe25017ab8e5486f9427218f4b1d824f1170795f3ef2805b7266d34c96e1ad51e49452ffc72c75b4bcd74c0efe8bdc14f7f45ab355cfcdcfa779d"
  - "SHA512:560a3885d3cc4ce302a5aadb437b8ebdfaedd4b8a8f75ea395dfcd4dca923d91fca185cc07023639d55a3b44c497f166b755d102f5d74a00c027b762422a7192"
  - "SHA512:67dec66be0a04890f14b928bcddcc4fe77d43202e086b6abc1ec8df3407973ed7bdfc4d9d31f5eff2cf2a72c0533f1c60267539253d58a4ffe525606b413f13a"
  - "SHA512:6f5f87fff33f13c5d7a1b726cc98ecdf7bb7970c094c44d456a53438b58be54c8c8f3d0e68cb0df95924f77a5aff1e7349d9995b8571c7ca261705a3279b6896"
  - "SHA512:7a9c07ae556061dc6644c04b1af9940469398c937664cd17978c3abf56080ea38f255827405e4d53f820526103e774e2de821f164d161cb5ac3c6ba9e7e12297"
  - "SHA512:802e02daf6ea0d20a87a6525fcce62154d0e3b1c2230a333541e81b4196db78413e50a7a8c416937edbdbd26a494ea724bf9832c755541e67960c42704752ce3"
  - "SHA512:825d14d7fe08aba0273dbb3401c0fd3cf48cb9341d7884be0fefe6d9b21f89cc0e6b27c9bea862a7dc56010c49a3a73b332cd7167c6e86b9aa2bc9f3917a052e"
  - "SHA512:88d2fa4bf37327f532f30db10e3ff047bab578a9304a213802918eea6986ab985bbe04f7d4be10dfd6516c8d23327c5237244aa055fea8edb419075a0a6be44b"
  - "SHA512:9216c6ff5934c2ed581a62029ce33f47474425a29070f826ab43461ed3faab1fe7d2594dcac96d1c1435880ec8f0645619d064f6a313c099fb32f6270daa80af"
  - "SHA512:9828c2a4d3ad7e7f347ea04415bdaf7208a97f218382bf42ac975ddaf2431479c12b4150fa523a4e0c0b01e10387c4d7b3e0c6fdb34ca799f34a58ef453b7e48"
  - "SHA512:9a8f94ccfda9ecd77a6f4fe08a678f494233fe62934f31fafee1d755e9573982ea17c780e789557bfb018ce9ac27487b57b2a6cde492ec59a4e547763cf6e347"
  - "SHA512:9a9a0c0818972b9696544fd1e74ae8306687ea6e819e805ed3669698d3eb268ecb52eb1d9f55fe6891373df8f0bef527c78ca20c5aff3717d1adb5e6a5f469cf"
  - "SHA512:9ad4436c106a5eb42b33af5e379ba877d1613040f874e10a344e824bdfee85f13919d4d70486c406252ed29e36ba137c08e87b89c20458adf54e77436614cc1b"
  - "SHA512:9c075b1b5e8bea3fc18ba587be89cbd163c4584093cc2a39ebb359866284a421b686fc17f378b745acff0d36be457d396df92242d5ad4618f26e6c2bfa6431e2"
  - "SHA512:9c7efe5cfb7efa08c1c8c9712b52d63bd020fc2dc8edb7621068d17feb16f09c4d6ddb4e3edc8bddc6068e343fbfbfd6b70b585474565163c5abc760295a8969"
  - "SHA512:9d0dad449ea0afaed0b7ada563845c782da2a1126d008d6eff8e7eeea554ba703bfd4bbc2cca710435982cdc3f4820e9e0f1ef6fe5cb2573e896d4c2d7d8ed2a"
  - "SHA512:9f5e1edd1accf45ad1944300b67b5f4a562178721c50ef40d9abd53babc0420713b87dc0d8e6f3e042be9f6dcaf3d1e18a36de4cf3267a5d42dfcb5fe535b66b"
  - "SHA512:a620d3b8e5f4f4207e8f107db19dd788d9784e4b5234db6da280288af88fb98b94ea49a4ef4ad9f03fdac2428bb5a3d1c269b6fe5b1f76019c33fd2cbd2a9c82"
  - "SHA512:a7980c4688379d6970b08ebc86d50c4f55b1bb05e68f376f7df260e67ea047facb3b0c55b659e85c9a4348466de4f15bcacfe330eb57f6c5c67712ba07e6d7f7"
  - "SHA512:a8facad92d8fadcd92cb9a6f135d205b35ba7e4f19ec304d234302c8eb7eb99b6c691a62f8116221ab164bdb43384f91a357b6ef11d59bba8afae3d9828cb476"
  - "SHA512:ae7dcece1b691b24885a15610448f1fb37848f64cacd551987196579f5698b8a633f8163e7307d3c5b4952f89d21fec08c6470a785f5ba32837a75a1c7fa0f9a"
  - "SHA512:b0b80b9372a91f3b22a0a4f95a13afc8172bd62128e7a67b28a913b3666c9b73aa5c09404b6c4577e475f011423879c92c7781682364dfdae32d9079509b2ec4"
  - "SHA512:b171998ce7a748bac6b8ad40819f535d7de1de96be00e1abacc0a0bc9fb3cf7ea12b06c4ca10fd2c485f8588511774954acd8b949c336fb2688aea56c5783ac4"
  - "SHA512:b2b6a7144c1d04cee2fb75897e0bcbfbc3367e4b0c75c1325fb972f0774612ce982f1d7b5692b2183635f6005733385dc093b5685d087dcc700dde601b028004"
  - "SHA512:b2e8e0028e27a35a0f19ecb6d2d36e7600f46b696e541f1430bddf630ddd428521ca8149c27274aed75589eefe7f4f735d5bd0eab13950b87e78dac70e7e26dc"
  - "SHA512:b3f6f275d6abeb47ee43981265b6392a35b513083afeb03e291a8217e4dec33ba9301db2c949c414a78af35f7d9d0c07e8793c54c81465f5bdd95f44f3ae8ceb"
  - "SHA512:b8abab6b5ede80415866831cf73f895bb86ece91ecb5af9bcec4a8cec0a297beebd60263e8e65fc2c70ead5b006cb6a24834a565f1b21baa2eccf128938bb428"
  - "SHA512:bd3248d00da156f405919ac880c62751b00150892661dfa760d75c2aa07fcab8eff6cfe1275d84ae94245d9d60e5f669251de8284f1595b782ded63d3e6b746c"
  - "SHA512:bdb918ca150acc9855536718f116b2bfe1a65e74a5df6a720bd804f7acdbfc5b33fe4bef9dd20ce75be56d3aab73ed4c1883685b453d08a177e9232f5d8f0363"
  - "SHA512:cbc805e8dcc1210f867c808db3cc5fdbd918f2d82519821766bc75c0cc2e4a346d2705005e878a86ef1f7f50a425d6720b5ccc9073180bc2567b7e4ac5fb071e"
  - "SHA512:ccb8c371f41f1efb43072b8bd1e1b31bb663f7756a0c0588c49c0480a4a020cad0627f215c1fc02879a1a73fa6c29984218271951b0359f7b5509810149ebafb"
  - "SHA512:d15c9cad1d07b4857fdd1b22d2327eb6bb81b74a649dd2dadd33d6715b84c376c4887ac147d13bdbcb051dcf9816418355879bb5d4fae22199bc8551af763424"
  - "SHA512:dab5017837abd7f9767dfaa857b85483254503103687d36bce61e9890dcacbf335c85f0544eb050fcad35f4e874f6fd9ac1c6cbf6c73fe8009175916c0287bf8"
  - "SHA512:dd38f99ee7a13a8d14d55ef7c22218d0b109d739c112c789ac2faf1c2b5b652a736703e6eff7484287efeb8e338004daa42e7bdcd05a59c0768c1dbdd59fa9de"
  - "SHA512:df4d13824d25560aa049ca7d268523a4fe0976afbac22f2bb2f3bfc8e0258ab80baaa1c35a300c9ff67da2dedd39dd2b660a3d624db2c32e002446fb11f26147"
  - "SHA512:e5f67e8cc46ffd96c6e523359a59e7e7ec2b7dd5b7a896bb218a313b9682ba19c2c97ac09286016d7a6472b84175c848aac08e3d7d3c09f4b23ae440ee5b51a3"
  - "SHA512:e714358a0abefa1109200200f59cbabe0d3c18eaa0f2d2b0f43fc4c2e48e1598a0c291becb034dc59701b1875d19af1a0d1ca6eba9b3638aa7db495318db4dc1"
  - "SHA512:e88937a722a332766e9adca0945134ffc8214c48d56fa95e0eea3b671fc3c83df18f3bd748f46e49e8a01f88a5b42c837452d87ea6697f7953071db273ce5fd9"
  - "SHA512:f67c0f4b144b5ce3277038abe8c083e8cb681a3320e2e01bdd6a7a9b30cedf824ee2b1ac8450174167b597c969784e96d47de97c911fb5682384265011441559"
  - "SHA512:fa0cbd8b7044ce5a2cad2520424a7fca0fec78b1f0356ec8fa40861626cbae584ce73f268492d550a5e3e7ed47b65ac50add208cca0e75360db55c7a0086c8d8"
jenkins_master_views:
  - name: kamailio57
    regex: kamailio57.*
  - name: kamailio58
    regex: kamailio58.*
  - name: kamailio60
    regex: kamailio60.*
  - name: kamailio61
    regex: kamailio61.*
  - name: kamailiodev
    regex: kamailiodev.*
  - name: kamcli
    regex: kamcli.*
  - name: rtpengine
    regex: rtpengine.*
jenkins_master_views_default: kamailiodev
