---
jenkins_slave_ssh_pub: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCDWUw/DLoSG7NWS/JpWxjl6dve2hOPPcR0VYuWAs78kszQF8I/HEo6owp7+w+ayVnQgiMIgtBAb1IRfZAdyFUo5JMsTJ/F1k8o9nh3dKKYXxkIMDBg6W68+E6FMzkhnwR3QZVDdgVtHwJMBL4uRXspZnUvR6iY3vsstM2O4T43qdkeCTw2UVyM+2eibdm1PiO1SSRsRt8R9hc9GvRj6OqaONalASfyLPcGNX9UTtH9Xz9YnZvNvkz5ZIf51xvzTjxelbUJag0PXAK35+TiIoJPcY/wwNCOSIrygYFx9Ay0H08wZzlvCdmRo+VzQYgHRf+YXr1R5mvLZMtaN/J49lupojP/mVpra1rM19nW+4ojRXVwYXvAszfs+ysAkYprYGtXY98/cgWwnJJ7DODEqerpwkQ96ZnkV0di8KmBUFdw/C90NeBJ1LwA3iOoe6OOh/B8pA7/80KuYRpivTaRZ4nSXiwxbVf1dJ6MgQR3bdusbL/ZRZr0PkzUuVBVWSBNvh7jPyb9jrunmZnoM+vZWg6LKUWplvbJHIGapKWFlBIskrhDsZunXSUtbnCyu0C95PZ+N+hy373RIGh1Xvkdg5zsJ2IJR5UJ8+fQDPgaQThKaPHEgyn76wZP+qNg0xOryEzVK39P1vNZGju01uK4WjeSkA1i8ukcAxSHhEPcglqLQw==
jenkins_slave_distris:
  - bionic
  - bookworm
  - bullseye
  - focal
  - jammy
  - noble
  - trixie
  - trusty
  - xenial
