---
# Ansible Role Metadata
# For complete information about all available options:
# https://galaxy.ansible.com/docs/contributing/creating_role.html#role-metadata

dependencies:
  - role: common
  - role: geerlingguy.java
    vars:
      java_packages:
        - openjdk-21-jdk-headless
        - ca-certificates-java
    become: true

galaxy_info:
  role_name: jenkins_slave
  author: Victor Seva
  description: jenkins slave role for my own use
  license: GPLv3

  min_ansible_version: "2.11"
  galaxy_tags: []
  platforms:
    - name: Debian
      versions:
        - all
