- name: common tasks
  hosts: all
  tasks:
    - name: apt-get upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      become: true

- name: master
  hosts: jenkins_master
  gather_facts: true
  roles:
    - { role: jenkins_master }

- name: deb server
  hosts: deb
  gather_facts: true
  roles:
    - { role: deb }

- name: slaves
  hosts: jenkins_slaves
  gather_facts: true
  roles:
    - { role: jenkins_slave }
