---
# Requirements for Ansible Roles
#
# More info:
#   Using Roles - https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html
#   Galaxy User Guide - https://docs.ansible.com/ansible/latest/galaxy/user_guide.html
#   Use the `scm` key for repos that do not exist in ansible-galaxy.com!
#   Use the `include` directive to split a large file into multiple smaller files
#   https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-multiple-files

roles:
  - name: geerlingguy.java
    version: "2.5.2"
  - name: geerlingguy.jenkins
    version: "5.3.0"
