---
# Requirements for Ansible Roles
#
# More info:
#   Using Roles - https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html
#   Galaxy User Guide - https://docs.ansible.com/ansible/latest/galaxy/user_guide.html
#   Use the `scm` key for repos that do not exist in ansible-galaxy.com!
#   Use the `include` directive to split a large file into multiple smaller files
#   https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-multiple-files

roles:
  - name: geerlingguy.security
    version: "3.0.0"
  - name: geerlingguy.git
    version: "3.0.1"
  - name: geerlingguy.java
    version: "2.5.2"
  - name: linuxmaniac.jenkins
    src: git@github.com:linuxmaniac/ansible-role-jenkins.git
    scm: git
  - name: geerlingguy.nginx
    version: "3.2.0"
  - name: linuxmaniac.certbot
    src: git@github.com:linuxmaniac/ansible-role-certbot.git
    version: vseva/nginx
    scm: git
  - name: compscidr.gpg
    version: 0.0.12
