---
- name: install plugins
  ansible.builtin.command: "java -jar jenkins-plugin-manager.jar --plugin-download-directory={{ jenkins_master_home }}/plugins/ --plugin-file={{ jenkins_master_home }}/plugins.yaml"
  args:
    chdir: "{{ jenkins_master_home }}"
  notify: restart jenkins
  changed_when: true
  become: true
