---
jenkins_master_servername: localhost
jenkins_master_home: /var/lib/jenkins
jenkins_master_process_user: jenkins
jenkins_master_process_group: "{{ jenkins_master_process_user }}"
jenkins_master_prefer_lts: true
jenkins_master_jenkins_ssh: ~
jenkins_master_jenkins_ssh_pub: ~
jenkins_master_admin_username: admin
jenkins_master_admin_password: admin
jenkins_master_admin_address: "address not configured yet <nobody@nowhere>"
jenkins_master_executors: 2
jenkins_master_options: "-Dhudson.plugins.ec2.EC2Cloud.sshPrivateKeyFilePath={{ __jenkins_master_sshkey_file }}"
jenkins_master_ec2_region: eu-central-1
jenkins_master_ec2_name: ec2
jenkins_master_ec2_ami: fake
jenkins_master_ec2_security_group: jenkins-slave
jenkins_master_ec2_subnet_id: fake
jenkins_master_nodes: []
jenkins_master_pkgs:
  - dpkg-dev
  - jenkins-debian-glue
  - jenkins-job-builder
  - reprepro
jenkins_master_pkgs_extra:
  - vim
  - zsh
  - tmux
jenkins_master_plugins_default:
  - name: configuration-as-code
    version: latest
  - name: ec2
    version: latest
jenkins_master_plugins_extra: []
jenkins_master_plugins: "{{ jenkins_master_plugins_default | community.general.lists_mergeby(jenkins_master_plugins_extra, 'name') }}"
jenkins_master_labels: []
jenkins_master_plugin_imt_version: 2.13.2
jenkins_master_plugin_imt_url: "{{ __jenkins_master_plugin_imt_base }}/releases/download/{{ jenkins_master_plugin_imt_version }}/jenkins-plugin-manager-{{ jenkins_master_plugin_imt_version }}.jar"
jenkins_master_allow_anonymous_read: true
jenkins_master_scriptapproval_approvedscripthashes: []
jenkins_master_ec2_ami_distributions: []
jenkins_master_apt_cache_servername: "{{ hostvars[inventory_hostname].ip | default(ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0])) }}"
jenkins_master_device: fake
