---
jenkins_master_home: /var/lib/jenkins
jenkins_master_process_user: jenkins
jenkins_master_process_group: "{{ jenkins_master_process_user }}"
jenkins_master_admin_username: admin
jenkins_master_admin_password: admin
jenkins_master_admin_address: "address not configured yet <nobody@nowhere>"
jenkins_master_executors: 2
jenkins_master_nodes: []
jenkins_master_plugins:
  - name: configuration-as-code
    version: latest
  - name: ec2
    version: latest
jenkins_master_labels: []
jenkins_master_plugin_imt_version: 2.13.2
jenkins_master_plugin_imt_url: "{{ jenkins_master_plugin_imt_base }}/releases/download/{{ jenkins_master_plugin_imt_version }}/jenkins-plugin-manager-{{ jenkins_master_plugin_imt_version }}.jar"
