jenkins_master_servername: ENC[AES256_GCM,data:BDcH07X8IR0jiI5HFSSAFep6Z2I=,iv:yD7gVLvBacdJ+toYlQwmS0PhjJ/vYaA5FAqEUYSVSo4=,tag:2mySueFO+N97BpzbzXKFZw==,type:str]
jenkins_slave_servername: ENC[AES256_GCM,data:5F9JvKaE6BYbehr3SU8W7QOgr9uVk5mn50zjkG6wnw==,iv:MN9Ma9OIqbe12joCbXp/uc5QPM8n8PX3k7hZ3R3mudY=,tag:1ztF4z/hkesuILV3Zjn7VQ==,type:str]
jenkins_master_admin_password: ENC[AES256_GCM,data:lq1L8sgs2qHDR819N+gkuTvynoI=,iv:lHgyhMgh32aChprU4SfCYx3Uer5OWykjrn0chi0JpuY=,tag:1dywnAlDLsb9iUpdh9lyMA==,type:str]
jenkins_master_kamailio_keyid: ENC[AES256_GCM,data:6KBPbuw7v0cEbp7dTqRYr8Qe0INRK/kgP2I9k/1sXynnUhH2aZ2f2Q==,iv:Nsi+zS31XUb4hoSNTCmbDz/Sp4QHNxAeObfOMDRxEF8=,tag:jKGyl786nVD+U+hIU5om5w==,type:str]
sops:
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2VxN3dyaVY5ODExZEg1
            ajgrMXFUMkpmUWtOdDZDakREMlRwUEZIQVg0CktWaCtyL1gyNEtnRjFlNGtTWnFO
            QUp1OXBxL0R5RG9jV1NjQ2U4RDRDSkUKLS0tIG5ZeW5LOFZjc1FnT3V1NFhlRDU2
            Q1lEN1p2UFVFdVl3bE42QmsrbzB1dncK9DceZX5HUsn95bA6LMUTLDru/HOd8V3B
            ievHn3whphCTEwHm0WhoJADlpp7pseixNPJhXKU5/X2axN/m55UqzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T13:04:00Z"
    mac: ENC[AES256_GCM,data:byNd8NQlf8u5DWXAjdIv0ihJ2kYGSyxmx0/acJHvFy5HzUu7EnG2mZyaQRZgVlN9Bh6znBN0vKdDCa7rjtRY4mx8zQbwYcaDcgnnDv9O9TlhJqeelCcd3HXg5kRIwJHEozfFZpo7c39dC0g1ME0jU1LfJBpfrxfZTUzxDNTf+8A=,iv:QRL4hRBlSOxbnfrztNrQnCg+1fsOCeb3q95LsitKIdE=,tag:3EKd1npLkyYV+IPbd4UdUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
