jenkins_master_servername: ENC[AES256_GCM,data:YcbXRphcphcBgat9+GYQkisBMCc=,iv:vjOmud4q6Ym8mvbIq52QAokbumAJCoC1RNXID4mquTA=,tag:UndRr56JtLnDgFhS8Nbnpg==,type:str]
jenkins_slave_servername: ENC[AES256_GCM,data:/buBvla105ulTSBsteOIm3R4loZAKauEHnuY4UDfaQ==,iv:l1PJjSKiONDxOuc/2FTjWORCP82vhFAIM+HrWfS9Ps8=,tag:13oFEykfkILJoZ16OQv3Fw==,type:str]
jenkins_master_admin_password: ENC[AES256_GCM,data:nOPgCQTmk3Y1ltnXjscmkpt8Z/M=,iv:SB9eAvgboIydFHmFwzcWfmFGcZQBLzhnKRQKBmv9C/M=,tag:Rfy2TAaMXLn/Xyas7yxN/g==,type:str]
jenkins_master_kamailio_keyid: ENC[AES256_GCM,data:3wxwOm98hcZwON1rC1OfC1v/Y7FR9QO4UnuZCOJvBEdwWR2fLovHGA==,iv:JQzyCSXdp2v1hXHdKwD5oRXhcmVCNRIcyhjYPne4ndQ=,tag:uZSANdtYSJP5fq4x9LLjNw==,type:str]
deb_repository_device: ENC[AES256_GCM,data:BwZI+/2wDmqAk3ZCeAflrBrtVju9DOXaTjPWF891omJuB6MS,iv:T5xyOnsF9pp1hBIOw0J1UIgCMLSzI6wTwzZY5zTeXLI=,tag:mlZMaeWJMxsfVbK49hLWnQ==,type:str]
sops:
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUlpReVI5Z0xKbTczOTVl
            elFLZHlVQXBScUMxL0dmdDVKak5Ya3RvMTBNCnliakh1UHdSSXVSYWl4TGQvZURz
            OS9lNmNYcGE3aFhUb3pjOExkZDdxdmcKLS0tIFVQZkhWM3lWUDlRZGlSSnRzaExQ
            MlROQ1V2cE9hNzRQMk9uQ251S1ZsWm8KiyX0Va9/pDnBjgzN8tfLU2OFtEY6Adex
            4ipy2C0/9H8ztX/SK4KQCEAEqNH3EHN05JVaaDYUFokhtp7BbjkrJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T19:45:49Z"
    mac: ENC[AES256_GCM,data:NyZL7TYCrkv/uK4rVjnRcccoRjn9/jNCHQFWg7BYFb/V9fhoZic3rvIhE8tAUMXxDQitTcuKp0lmlymLBcIr78oLKLKEHLbFH3smjuAKuf3aEp5UahigPw0hhn4ghiBW6O3pzDgxpBhoYhxklaEJvDakus9VSQxGfLkYnr+FlWU=,iv:0aZZMnrz5GxudLH3CuIoJoan5y4ZnNfa4D5fe6tMOAQ=,tag:qA9AlXCQgsV/32PyC+hV3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
