jenkins_master_servername: ENC[AES256_GCM,data:OBbRzzi4ZxUag2EVFTYGi/u3pa8=,iv:BpazR0yx4Xjn5ojrWgffzkYD7uWIROy5ujELArEknfw=,tag:QULLXTqLI41v5PNy7QlAzQ==,type:str]
jenkins_slave_servername: ENC[AES256_GCM,data:OhLyPbq+uhz71KOgsRwzUfOdFGbykyaOjGgjFtffJw==,iv:bt/b5upRgnp8pC8FfCNzGKy+wwWDUaYkFl3bJuqP2vU=,tag:eglwuWOS2Nqkw/3ELo/zVg==,type:str]
jenkins_admin_password: ENC[AES256_GCM,data:xi2pCW/D3B3/X+tPtLDnZUf0f34=,iv:Py+tWKGznf444hmhCb3HPAQ7qqquyKdAgmfdtow9vlk=,tag:4ycZ2C+7VVDBJTxZHlfiqQ==,type:str]
jenkins_master_kamailio_keyid: ENC[AES256_GCM,data:h+KcOIeOzRRx2Gf0Vw3TSp0N2dr2I+pOTFXmoXkWt8dSEReldpF3Rg==,iv:3uakyC04q6YS8JdLkRKE34iYEN7ULr9+KtCawkgT814=,tag:7Cbl3+WLyZtzMnWvC3aVwg==,type:str]
sops:
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSVM1UEp0ZmVuNDRobUYz
            KzliRW9hcE1vK0ttN3gvVW45WjZ5NWdGT0Q0CitXRUlreUlZTEt1QldDRzhlRHNV
            aHVjMlpZKzdPb0lVRi9iRTZscDQ2Q2cKLS0tIGdpTXF6MGZxVXNjSDFxWmhtLzVw
            Qk0rUWFqdzhBcGx3OXNSMHFYU3locjQK4UliTK1/DV8jfjCr8Jidz8K7YPq8vtkw
            li6dW/uS3vaieYNZycLXHAI8U9AEqGMUOeNGTMON13QkXn+6riem8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-09T11:25:42Z"
    mac: ENC[AES256_GCM,data:ZB7hgac5cBXRgH4hmrO+3holq3VBEy1W802V1QpPU0FoM3EEB9CI4jxhyOWsswdJ/aebNMM1kzUnAAWWfYaXkJKNDwry4ncvydSIn7dfFNPStU/31X0onGMLBG87U5eJEoSG5ESUNs8LeVGQtv4dmUuWoRaOceTOm+t4xzShNWg=,iv:xN+rs5+op36a9DpnrrHfyXXU9XEgN8wgFTDAQj/qL/U=,tag:nQB/LD6ukWwH8CS+79K1og==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
