jenkins_hostname: ENC[AES256_GCM,data:GQwE30CI4c6IJpjiUf3WzL9D25Y=,iv:ZJcJIs6U30F6cpuL9/sWeIK1NMSjITpaFB5n6mOi/2Q=,tag:kkjaVVpWP4hb/68JY8NUeA==,type:str]
jenkins_admin_password: ENC[AES256_GCM,data:B7xLt7eoxyU+jNis9MtCz7ztGTs=,iv:AeahSkVtmHjabZfppH57ULzwRbRptZpsCP5o9Vaa/lo=,tag:4w8qBFShaRlIHrqs+CAvYg==,type:str]
jenkins_master_kamailio_keyid: ENC[AES256_GCM,data:OuQtkvaTBz/FDTvy30ANnfVSfxn4s9Ue689tnMTZtQKpgjtqo49mbA==,iv:vwPqv+uLvRxOPDSEyrxuIIv8JLFM/Li44u5CzSuN3Zk=,tag:kbzVXkrC0n9StQdbJv4w8Q==,type:str]
sops:
    age:
        - recipient: age1lpqp7ue6rj8x020uvlrklk2pz6k6va80qh3c7fzce0v7gq2m3akssrfmkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bUJUVEp2SVd0MHdTSHQx
            S1lJTlpqNk15RHdZblV1NE5EVzlMdEhNV0NzCm1hMW1mVEFPaHZJdDc2b2p0OTFh
            Q0pudVg4b1RLdnBuN2VTRytWTWg3YnMKLS0tIHpzOE5OZUhxVDRkSk9wMXJOT2wz
            bjM4eVBocHVVUjV5Z2UzNEpsb09uNlEKc6IO0XO/rVYLAq603EEefjfdAPKCB/s2
            EAsqY1+3WW3TuWaYfUkQitZzfbJQN8hOTdWWVBfdLEPTvkWkNI1MPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T14:58:31Z"
    mac: ENC[AES256_GCM,data:DJoGKdmGGPCfriRRbRUIMlLJN8eGKN6wCnW3PVrwahniWIQME5AF5ayPVmgnmMqCSE1EeZWdwAgjSUmQe4QM4yT7wbRkqwuS//mBdSng/9IXFz8SaPf6BtsVfWbDxbrGoPXyyZcWgK7hLMi1euaLye5zGGGeOXu1jP8fPOJy1d0=,iv:jHQPsqLiu80twZ06/bkbrmlUmtLFrwpdqXx0UmxIjvM=,tag:SGFX1pDVbihxVgbxl7vkOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
