---
jenkins_slave_ssh_pub: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCbSjSZUAuPv70Pu9Xh8CBB2VHMzDyyDyVmiGD4iFeqp3y9MsaFHW1dGK60d5Mg6VvvyTGfoLrH62MEo0RjIh06ZFQ6rLLrYN84eHm1h40+sHXcGlz0UmjWaJ9l+WSiEZPtKMoxdUKgu2EgXK07n5ZOY6isiV/ANDLOwAXE90vEmsxjwGxXet5MkP0wGfy6iKGLlDiYl6kvZ4zYqOKDlUVnj3D0IzvrXf/BDYuJl2bfBEclFVEO3/RkoQGV9Hd3M4LbcMgwLtcorrXtPFHheuOlr3Tu/pTzqWGqThpltxlZVZ1GjPFIfD5XFou80ZYek5TuDSHSXHfkFHk2uP+JTrdmTAVlG+OV8FuNMDX21pkxpEj8HwvJEuxwwXAlCn4l9FuRGsOSjPbxmPQeWL4HAyz3hbyC4yTDxRq5CpE6jVW6MP9RSbEaO/FkxxqvhTeK2qE8UzZGT03Yqi3e71ipZBOLYSS/Fg8Fy2rEcrzW2E+4eMBTOU8rohR/J9uJN/1eO9+CD6qI16i3Kyig6W4t81Z05ZqxhNRwdNxiZm7jmouhHvmzfFvapbMvmHYpgKDJxLW5H1U1graiF89Rd8K1NWTfcgD3dObPfhCTmCixOaa1uGe3k2zpIvpd6Ys9WDvew0bXP885bort24qBySabMYt9UZeKFMnC9kCTrugssVqajw==
jenkins_slave_distris:
  - bionic
  - bookworm
  - bullseye
  - focal
  - jammy
  - noble
  - trixie
  - trusty
  - xenial
