---
jenkins_master_admin_address: "<vseva@sipwork.pro>"
jenkins_master_executors: 5
jenkins_master_plugins_extra:
  - name: workflow-aggregator
  - name: git
  - name: copyartifact
  - name: parameterized-trigger
  - name: build-name-setter
  - name: email-ext
jenkins_master_scriptapproval_approvedscripthashes:
  - "SHA512:04f22cbe9804ea9793b3a8fbbfa5f1b73a67cdd70e86f5a44c28d43390321cc374104dfb7e94cea46c83336ec01277b1a92d0762d6505200388891902976601d"
  - "SHA512:0f630a12ba36d6b73ad2d2d993f1827492eea9cf20a728d605c9f3c65120ba13da46d0c4014b2a63069fba83cf82141f578b8aa1dda5e0c97249a5b77da30cfc"
  - "SHA512:1f9a9f39d987e3391645b2af16a5b691f2d706b7f93c086abbf70e263329d37206ebb8ca8a8a7026c2bd0d10d8d03b87341bc2f96f33a267a6a82c0b01aa0872"
  - "SHA512:26658f937151905cf46ab426ff137d4f02a7bea3c14b25fa6b5f2ff744f60dd2af5b466a7aeb3d94efa54a53e9e7b481da96c96aaaef9ffe14b85f8fb29705ff"
  - "SHA512:2c3506ee075858fdaf61b1f3aa5cee5e92327c3c3265e9526365c909be3451bf21a1b8745e668dac33435643a005f1e133aeaf429965302f2b91727b114913b1"
  - "SHA512:3221c680ba29019b480c19ea56450bf00586c67abfc9aac84be35dfab56adbcc57c7dc14d19ae01a51f27fc291c88d91a7af2c06cf5b9d2e7764b0bca7705363"
  - "SHA512:3d02ebeb657e7bfe2e8157adb954d328e765dbc2fb82ed13ad54cf4ae7a43834d5f4d4270fe05999fece809cfec372e244ac6312be21e25dda0c373037da7961"
  - "SHA512:40dbde4c5053975b82a576dd3a044c55e239896d1bd282a7d405a7964cace7749a17976b05186d51b7371e14143746c23ece8f498e7caaa0e3db70d6d50d7256"
  - "SHA512:463a9e9339b7690d0c42e02f7e9e8655669f819c439ee0c52a9381126fa8f9376a9dd195ce5ec4f2a02fb3e250a19bd9f9d36f156a0444d2f82bf5740daa101d"
  - "SHA512:52ca060ad538c4991d3d673f501ca230950128b1b4f38276f151d4968525f93c8cfb349d7eb49c80fd00926b04ec9981b6c0a96a87c3fdf21529a96e4d5fd0f3"
  - "SHA512:598f10e2db5ddd3f12939d075c0b3e5271c100706a27a4447b9ef72261a62e81d6cae4270d306d779652dfc7489dacf7cb6cd1790ec4c99b384af5937387429d"
  - "SHA512:6526f44bdda29089be2c7ecd9feb691e04ca1c68567d4a03e99bf4bdc5211ab32193a20cc5eb628581aa72207e63d5908bf4c88e6c72283b803ea455942c693e"
  - "SHA512:6740414be3530a954ff4ed8260fdc8e07a8ab602dfd5840ecc1445112f2ba6a83e19318952abb5bef9cc394e348e9b83f14d4ec5b7c701654050d53eb81be1ae"
  - "SHA512:88fd6bc550f59de44f9fdaa9b8b08ec8bfeacafd4c2e196b35b7244c513435c21525de179e9eec6640edee1e0f7e8f039dcc3626213b8c371935fca811603171"
  - "SHA512:8dd645656c8c12a99ffbdfd82baeaae82c33c0ffe778d620e362e30692e2fdfb0550447861f0eb5cb859f3647954147de82a5472b198b9d933ad21ef4914a2e0"
  - "SHA512:94f3f629733f8441edaec122859be32e2b70b4fc0693007d405c19eae1fbd03a43a5ed41d348ab443974dc3ebdf93416f074abfbf8f343612b9fff6c85eb3029"
  - "SHA512:997d298da2d2de0452c9ca42150c5e55930041b6a9ff92199f58ffbaf0fde34f15dcbc21c984a8541617675857934868923b1634fe10d26a36fd377a63b2569d"
  - "SHA512:9e45fb513d283a8a1ba7791bc599a99b0c68418f3a3ea75cadcaea6283d08b96157f088e9af5419eb5e817b9418d9e5e9b77a0b81157e77e75c55cd692970475"
  - "SHA512:a005ce66e4301ad739a6d1f3bf96b0a75059a914e18bc5bf4e4c6c420f52ba6ec06037fe743dfcb574bc40a092742f919f01b36c69503e08a48c42fc5d90289a"
  - "SHA512:a01f8f6c035b5525b77faeaac9abae0db502bc71315d21d9348c3bc2e8f0d6ec086cb0a882e8e46dd25160f8a0b736d8cad1afec5a5337939fb8923faffa3ebf"
  - "SHA512:a3536bc47b925f36c16ede0f4558052350e2560a6c6f88f465be74730f31a8a9b4a2bed4af7c307d4242a12a2be9afd8c2116adbd3edb0736b50db0abcb6d395"
  - "SHA512:a390afa10248721efd1cb6be78e7152af3159312bc51f9a4607cb5da284d5afa9091cab42cbfe8c03668be2d08e5ce42cf9a142c9ff765662b5c76d0cb1f7436"
  - "SHA512:a703545c6601cc37cc538a8cc5efd374f6f07cd76e6f85907b7f3e95dd37016f96f59da0a6db8d6bcb30cded4afb524a86b8b06ec0e21fb3b6c2539ec6a99556"
  - "SHA512:a95b950197c692f50f106aba2e6ab94f0c3ee2f126d8c06e1435d7e731151bfb7f3538d8527a962261c1f006b0d518c09ce28c096f1ebe3dfd4ebd5475aa21d3"
  - "SHA512:ac019799b4c0be089124183471b436cb01a1c5d233cf49b2684dcfe1a1d61c71608d1ccf256157548218072a99d818c851138b792ef22abcc8dd6a24e05ffcf5"
  - "SHA512:b1f16039bec20cbcfb6545c28f7342a25ded7e37e40194b965090659bc8b7768e3498dc81a8b6578736351cc3bf5f097825dc0001be0542bf4fa586a024b2e4e"
  - "SHA512:bae6b838b414ec5d2b9fc86355b8879e1ead9fbb35c69732df62e0cf33b617738b100036da5beac2542865ac851e18d6f63e64be7f127bd29f832cb9fee0eb8a"
  - "SHA512:bfe4fd214ef4835d3471422f2061e85168ce45e9ed6e1ead9274b16a77649ac525038940be50646e5586cd6ba2c0d3db425db1811f1a2eea17e15dfefb3623f7"
  - "SHA512:cc947fe21bc421d7ba787097c9b49b054beb6912ca8ee890ca563edbc556bfb7a7b096eaf88adca812edebea8ee4223667974c1b656fefec2a4f03473194b2c4"
  - "SHA512:d145f86f9de3a74c05924b52720166b40fa29bf925d4b49f4a1020f33670727c96d153d8a28ec77064b4e9ec681744ece8503d024b41bc4c4e274b24d38e565b"
  - "SHA512:d9d2d762c2ebf50a7806f6437c24d99c14771b28891fd36731c14b27833de4c4ebe4221e3618ad9e3d06fd96f2a0f28d79e69477c8eb664027742108acaa4680"
  - "SHA512:e5ed1572162afcef504395dc0726a41a6eccb197f511e82d3368c8a0d6491195b3033d1713a39aaddc32d09c5ae43e5826457663c93fffb2745cccab897ce89d"
  - "SHA512:f19806614626ea0a3b9a0812af72b691ad57578f143cab8b8571bdc2dd1d978c22fe0e49a5155fb0dbda54302a954917e4a9f6d0806a9774aa5066cbf067f2a5"
  - "SHA512:f39c94b5c5f22099c6066b6230daf124ab1d031caeeaf2e6933e9431eb64f5cbb14197d3a0f716982b6704407bbcbf8b57ce53806392c475643558827cd5707e"
  - "SHA512:f9c700288432a78e5c08519f0178b7369466ebf2af281c3d3593c1dd82236c0fcbebdb353f10f037cc4d439098e0bf1dc66c5051bf466dd203e5d5e533edc837"
