---
jenkins_master_admin_address: "<jenkins@kamailio.org>"
jenkins_master_smtp_port: 587
jenkins_master_smtp_reply_address: no-reply@jenkins.kamailio.org
jenkins_master_smtp_tls: true
jenkins_master_executors: 5
jenkins_master_plugins_extra:
  - name: workflow-aggregator
  - name: git
  - name: copyartifact
  - name: parameterized-trigger
  - name: build-name-setter
  - name: email-ext
  - name: timestamper
jenkins_master_environment: production
jenkins_master_ec2_region: eu-central-1
jenkins_master_ec2_ami:
  - architecture: amd64
    type: t3.large
    id: ami-0b31c2adc9e7be95c
  - architecture: arm64
    type: m6g.large
    id: ami-0cc545d8a6da84f78
jenkins_master_ec2_name: "ec2-{{ jenkins_master_environment }}"
jenkins_master_ec2_security_group: jenkins_slave_production
jenkins_master_ec2_subnet_id: subnet-01610fec8f69c035d
jenkins_master_ec2_ami_distributions: "{{ ec2_ami_distributions }}"
## This configs depends on jenkins-jobs repository values
jenkins_master_scriptapproval_approvedscripthashes:
  - "SHA512:06affa7671be385edb4d9de1acdf0cf608739eacfdf84222c916fbeb381946caebd4ad62dc023f61cbba4b7eb03bec010828144d8bb74d95f04388dac5140b10"
  - "SHA512:07358060beff2cf106a0599e94557ee1fe239d0d679c61e82e7d6fd3785cb1d232bfad4fe6829dfab5d5596d1d6a77f314b1f1fff6ff20b014e7a6a34870b7f6"
  - "SHA512:09a4e935000d7a71dfb2458ac9bd7163f362ac00e13d0c446ac54fa4d23e070eca83e08c24f8ec23fdefbe42ebd074db978899227e91ee348d01233e0bb8a42a"
  - "SHA512:0b000aea3f3a0aa58c2db09aac2f983e4ebc2120f5a446c428724cb6e4c392883e48c6e6881e8a4878ea1641184e99aa433a50aef0bc451a08d07e2ccf4efd98"
  - "SHA512:0ec616e9949d67a82aa27020958668d4b2bf89410ae2f6597d6c5729b6953820aac94beaa1233cdf31f4ccbe1e24932d037fab76394c9f27cd8915d957eacc96"
  - "SHA512:1a079f97f1b7796f5ae6ff3e21f4ae376eb9ddd847b30fc59d482d0b4a4d58a418796739136f43903299a39f26584e6b11e4a1cea2117cb1ac4be554352926dd"
  - "SHA512:1d26f63f4eb384a946ebf5d50924a3758c803054989645e973710edb2752d13a1d7fc04ea954713990645f3ea3e1fbcb806c6b9a63324cf63ff54065aa553273"
  - "SHA512:2087d61377e677f62be4e79a8acfa70f5411657d2d0db571d7ea8fe99f9e33005304deac7517be1a43ce50275832c2f1883e8f28d9dc1ae0f2a6be55f6d5e3e1"
  - "SHA512:242f012bc60ad25cf03b2641f2515aa95dda4e06c113774d51326b1b21d6c40c15f85bd4806b463e7d1eefb92b0476926003fb77c59ae962257fad8c8a7fcaa9"
  - "SHA512:27a3ec37b87684f5f47b77d558262f17867ab7965e1c6ca6e6ddc5f373f5c5487426e12644075bd22dfd61474df90325797c185bdfe9916d4673dcb1e175d05f"
  - "SHA512:2a4295cd86adc09abba91ddb357306fde89f6ee58c9c909d793df1b5751290d7aeb7a4e06fb42f4c8fd513e03d17bdeed1b43434e375ce75edf542e77f9ac16e"
  - "SHA512:2c32b37c83bf5bd186c6d0b60e7321dacb98c4cdfd7167aa484eea9d22bd1ef4c5eeb95cc966959724a86b6b78e6be92af4f311041601349f048e396d8789ca5"
  - "SHA512:2d60228c9c0621133d5b387133e6fb521d1dde65cfdf9480835c38401225d0b97d1e634ea79aac42eff7d8e241b0d26ca11ccd50f22f818026c2149ad90d49ed"
  - "SHA512:2f2e23bbefbb795cdf720d2ba68d1cb0edc88dbf492e09ab34ef61f0055d6e8f4f21c57d52e044ea3178c9e918298cd7e32fdbe60659594c48dfc2026f0aa98b"
  - "SHA512:35b1ce6d5fbdb3b555da4c8e34d7c299c432477d99d827c350a0607e066278f357d0707cabc90538386b5a191b6f18a2ea1be60d8b691a675ec0db93d80e15df"
  - "SHA512:389aa511f19d99873504e3da7afa196f13d9ffa44fa9e4c9a39ed7c613c829a430709f9fab5b736b1b49a7921500b3d741c552eced9e8e5e11866326b41c8b08"
  - "SHA512:3a8269214d0c2474d0f200fca390f928a26f4fdba7aad79597ff53892a26f862c7bfcaff1cdb1e5a4327c25eadba4e0521ae63564af3fa6372691e9774f8a9b8"
  - "SHA512:3ba5c7b7b5ff645d81885401d124e168b9cb06cd8bf8a3b2ced64d677277bf8ebd4c218abac48756b8f9e30711348b52f913d731b66b94acaa81d9b9c0e9c6fd"
  - "SHA512:3eb5b1a8993b1fc53834b77afc437c1dc4defdd432a23f8b34e14b909ae7cd4efb31ab014f29000cd38275f9b50040ac915978ea85c9b5a1ef2cc8fda5a5cc5a"
  - "SHA512:3ee6fdccee52517da1935892c7554e4d9cfea69b84b3a4e611a1ba70b3565386e88ab70adda33171ab672708c8cc2079708914aba2ab6b658864194d9f032476"
  - "SHA512:48441522d2b8177c9c22730fb276340bdaf8f6e9f7daa7767d15a6dc820e3ec6ff8b234972cc93ea559550ccc0940fa043848d76bbeaf561874ebbea3ff72744"
  - "SHA512:4a8ef6ff0b349f5163f046c95ea5e1714c3a0da1063836f922c1e62f261ca00d00fd2c35b67b55bc6c108b1535ba6e45e7b0cc17ffaf535aea9b5d57345a6cee"
  - "SHA512:4c5b5a90f5fb872e4253d63fb6bfc229ef70d9df5855caef462ee14bcf8af71deac038ea835fb541cb5a4be8b89f324eb776b347e7ef70643f2fd0e32c614c9c"
  - "SHA512:50934928c5f66900df43d919b3cd3e780fdf68cdae34390a69bb5f3f0adb5d6bf2371bae4cd0d3b12868cc2f4bd0c833a69c745afd03c1df29958793bc175740"
  - "SHA512:5174affa4bbfe25017ab8e5486f9427218f4b1d824f1170795f3ef2805b7266d34c96e1ad51e49452ffc72c75b4bcd74c0efe8bdc14f7f45ab355cfcdcfa779d"
  - "SHA512:550d33eda2b6f0c7dfbaa1ee3d7258b21b66db27766223ea03d43ecacfa7c2d09a1ac478c7b3452009368998ac526fdbee370b2bf0c85054da343c89e7a155d6"
  - "SHA512:560a3885d3cc4ce302a5aadb437b8ebdfaedd4b8a8f75ea395dfcd4dca923d91fca185cc07023639d55a3b44c497f166b755d102f5d74a00c027b762422a7192"
  - "SHA512:584c41fbfa8af433a88fd90510f9d0075a243d17a3740b3c6f79d9744d60e929eb2cd99fa6c16f44d21b96583d65f1c4857d958eb7547aef09099374d5d6ca2d"
  - "SHA512:67a021b7ce9d83fa46f3a6e094863c3fb18ce1dbd3edb9586a2086b3a429c5fc0b4e74b933eee94aab5bfae2d78fa151f79c1134cea4e64fd656180d9d7002ae"
  - "SHA512:67dec66be0a04890f14b928bcddcc4fe77d43202e086b6abc1ec8df3407973ed7bdfc4d9d31f5eff2cf2a72c0533f1c60267539253d58a4ffe525606b413f13a"
  - "SHA512:6f5f87fff33f13c5d7a1b726cc98ecdf7bb7970c094c44d456a53438b58be54c8c8f3d0e68cb0df95924f77a5aff1e7349d9995b8571c7ca261705a3279b6896"
  - "SHA512:75c98ef0b518ce51fbb009159951bf00f2cfa7a00d1befbbfac2eba858940082374c3db6969b02421a568417b86f2b49988370e618f35f0c6c665761bca717e5"
  - "SHA512:7a9c07ae556061dc6644c04b1af9940469398c937664cd17978c3abf56080ea38f255827405e4d53f820526103e774e2de821f164d161cb5ac3c6ba9e7e12297"
  - "SHA512:7ba6d30286d6ae5581a87aa2bf4f5aab7486ad44b635f16d316bb7bdfc32f624985d4d2445ec8ae47ad624b4e8039c08f3ee1cec25f76fdb2d5b208ab4d31b56"
  - "SHA512:7ec717fe1f8855630b70af6211968f209f4d5be4ebd26aeab26d79993b41aa72d36493cda98b51f9089fd74fdad3b42bbdc6af409d675440f1f2068d11491bf6"
  - "SHA512:802e02daf6ea0d20a87a6525fcce62154d0e3b1c2230a333541e81b4196db78413e50a7a8c416937edbdbd26a494ea724bf9832c755541e67960c42704752ce3"
  - "SHA512:81afcdc87371f2574db6ae0fad8812ea396c1a00f02da37ff3dabdd28846408a9ce48984fcedddb3d7313a1c57e68c3a966e8776b453a1084400679b64356459"
  - "SHA512:825d14d7fe08aba0273dbb3401c0fd3cf48cb9341d7884be0fefe6d9b21f89cc0e6b27c9bea862a7dc56010c49a3a73b332cd7167c6e86b9aa2bc9f3917a052e"
  - "SHA512:8477ebd2e381c2a2e08faf5f169d751d04b9b328c424e61686664f06a4bf431061b438d008c77d709c4faf46d0ac31125dc9a651ae87bd9224782ad1b6fdc143"
  - "SHA512:88d2fa4bf37327f532f30db10e3ff047bab578a9304a213802918eea6986ab985bbe04f7d4be10dfd6516c8d23327c5237244aa055fea8edb419075a0a6be44b"
  - "SHA512:8f3161445ee5e101965899a0d31322ffd7d5324613733bfb1ce3d87c183d366ff18aedd33a0b7d9d9a6495f12e88e3bf6382e342e98c9ea4fc503108e9ac76f8"
  - "SHA512:9216c6ff5934c2ed581a62029ce33f47474425a29070f826ab43461ed3faab1fe7d2594dcac96d1c1435880ec8f0645619d064f6a313c099fb32f6270daa80af"
  - "SHA512:9828c2a4d3ad7e7f347ea04415bdaf7208a97f218382bf42ac975ddaf2431479c12b4150fa523a4e0c0b01e10387c4d7b3e0c6fdb34ca799f34a58ef453b7e48"
  - "SHA512:999bd25059065007c7519c997eb9a5c17da96137ca9d6ea9ba64ebf8ee0b236d07ec2003c2c35589a7513dba163e2e01332090b8ed70e4a9fa28f58dda53faa5"
  - "SHA512:9a8f94ccfda9ecd77a6f4fe08a678f494233fe62934f31fafee1d755e9573982ea17c780e789557bfb018ce9ac27487b57b2a6cde492ec59a4e547763cf6e347"
  - "SHA512:9a9a0c0818972b9696544fd1e74ae8306687ea6e819e805ed3669698d3eb268ecb52eb1d9f55fe6891373df8f0bef527c78ca20c5aff3717d1adb5e6a5f469cf"
  - "SHA512:9ad4436c106a5eb42b33af5e379ba877d1613040f874e10a344e824bdfee85f13919d4d70486c406252ed29e36ba137c08e87b89c20458adf54e77436614cc1b"
  - "SHA512:9b21fe2cccc19e3ee90cd0de040d53501a8750f530d65762930f86899457567245c81dd630d6e379a55a143d8b9ee46901ae2109882731cc73e768858118101d"
  - "SHA512:9c075b1b5e8bea3fc18ba587be89cbd163c4584093cc2a39ebb359866284a421b686fc17f378b745acff0d36be457d396df92242d5ad4618f26e6c2bfa6431e2"
  - "SHA512:9c7e4bb333978ae94a6b257b5a2992ea48797e76cbb987109fe56df266e88015bcdb8e4763ae33b1a5335f667fe9324eb709e7f065c1cf23628d0146dcfc6372"
  - "SHA512:9c7efe5cfb7efa08c1c8c9712b52d63bd020fc2dc8edb7621068d17feb16f09c4d6ddb4e3edc8bddc6068e343fbfbfd6b70b585474565163c5abc760295a8969"
  - "SHA512:9d0dad449ea0afaed0b7ada563845c782da2a1126d008d6eff8e7eeea554ba703bfd4bbc2cca710435982cdc3f4820e9e0f1ef6fe5cb2573e896d4c2d7d8ed2a"
  - "SHA512:9f5e1edd1accf45ad1944300b67b5f4a562178721c50ef40d9abd53babc0420713b87dc0d8e6f3e042be9f6dcaf3d1e18a36de4cf3267a5d42dfcb5fe535b66b"
  - "SHA512:a1b5c816cf51adbd89f0f1869fa0d7cf646ba35f0fc1fff6c811616a01049d4156bc5d7e71a4a24e1d9fbbb0443eb9eb4e4d0d7359eed447da073f8012b79a83"
  - "SHA512:a620d3b8e5f4f4207e8f107db19dd788d9784e4b5234db6da280288af88fb98b94ea49a4ef4ad9f03fdac2428bb5a3d1c269b6fe5b1f76019c33fd2cbd2a9c82"
  - "SHA512:a6e0505938320848f7ed315a28f546b44f9e9a42bfc404e5a6997048c824023ffcba8964ff8ac859d57642c52014b43e2cdeb17f48d988f2c93b6b66e62f8bf0"
  - "SHA512:a7980c4688379d6970b08ebc86d50c4f55b1bb05e68f376f7df260e67ea047facb3b0c55b659e85c9a4348466de4f15bcacfe330eb57f6c5c67712ba07e6d7f7"
  - "SHA512:a8facad92d8fadcd92cb9a6f135d205b35ba7e4f19ec304d234302c8eb7eb99b6c691a62f8116221ab164bdb43384f91a357b6ef11d59bba8afae3d9828cb476"
  - "SHA512:ae7dcece1b691b24885a15610448f1fb37848f64cacd551987196579f5698b8a633f8163e7307d3c5b4952f89d21fec08c6470a785f5ba32837a75a1c7fa0f9a"
  - "SHA512:b0b80b9372a91f3b22a0a4f95a13afc8172bd62128e7a67b28a913b3666c9b73aa5c09404b6c4577e475f011423879c92c7781682364dfdae32d9079509b2ec4"
  - "SHA512:b171998ce7a748bac6b8ad40819f535d7de1de96be00e1abacc0a0bc9fb3cf7ea12b06c4ca10fd2c485f8588511774954acd8b949c336fb2688aea56c5783ac4"
  - "SHA512:b2b6a7144c1d04cee2fb75897e0bcbfbc3367e4b0c75c1325fb972f0774612ce982f1d7b5692b2183635f6005733385dc093b5685d087dcc700dde601b028004"
  - "SHA512:b2e8e0028e27a35a0f19ecb6d2d36e7600f46b696e541f1430bddf630ddd428521ca8149c27274aed75589eefe7f4f735d5bd0eab13950b87e78dac70e7e26dc"
  - "SHA512:b3f6f275d6abeb47ee43981265b6392a35b513083afeb03e291a8217e4dec33ba9301db2c949c414a78af35f7d9d0c07e8793c54c81465f5bdd95f44f3ae8ceb"
  - "SHA512:b6c30f8060355446e053b461304436ddae7188b9a016da7e5de6eb1e5a09b052db090a56f0f02e5de7753d5f8f5471ecc35e5d656420097da330be4e506c4e4e"
  - "SHA512:b74762365df9f26b05aec43b522b1ba4bf9e4f2ca822e81f701da27f8f8caadc6d887c9205bde3860a54117e907f20f88bc4f6cd6a270aa8c7ac5f78c98818ba"
  - "SHA512:b8abab6b5ede80415866831cf73f895bb86ece91ecb5af9bcec4a8cec0a297beebd60263e8e65fc2c70ead5b006cb6a24834a565f1b21baa2eccf128938bb428"
  - "SHA512:bd3248d00da156f405919ac880c62751b00150892661dfa760d75c2aa07fcab8eff6cfe1275d84ae94245d9d60e5f669251de8284f1595b782ded63d3e6b746c"
  - "SHA512:bdb918ca150acc9855536718f116b2bfe1a65e74a5df6a720bd804f7acdbfc5b33fe4bef9dd20ce75be56d3aab73ed4c1883685b453d08a177e9232f5d8f0363"
  - "SHA512:c2d9d264da28826fa8f3172146a75bc54bc9c292560eed3c3afd2ac9615df04800c192c57586a78887d8e25feffc08b5c285df60bf16d5ad03f6922b4731f1c2"
  - "SHA512:c2fdeee71e148f53f395661581dcb19f58cb117eeb76a8a05ac5fbcebdff9d50fcca6a0adc0d4d368453bdc200a29f051c9e819af5851404b99a8afe2293d144"
  - "SHA512:c42dc15deec2035058dc475348969822f5cb0be42426072e8fb202f63062a3d76fdd0f68e4f4e8ed3197fef609d3dd9bb1f0c4b42c9657d1687d272a0a4ae4ab"
  - "SHA512:c5c562ee3e454d01cf4db8f8a55eb2852b07ea8d05eb7e3bf6e2ee216ebb972fbab0cee03cdcb9cab973cdc64f8bedabc44ad62f7d5bfbbce497c75c20561418"
  - "SHA512:cbc805e8dcc1210f867c808db3cc5fdbd918f2d82519821766bc75c0cc2e4a346d2705005e878a86ef1f7f50a425d6720b5ccc9073180bc2567b7e4ac5fb071e"
  - "SHA512:ccb8c371f41f1efb43072b8bd1e1b31bb663f7756a0c0588c49c0480a4a020cad0627f215c1fc02879a1a73fa6c29984218271951b0359f7b5509810149ebafb"
  - "SHA512:cd434cb4909e8a1923a860d30026c5ac845c1eeeff7cf2d06860109f58ca73524f1f746d4ac0f0777ed03d80e40a0b8d910f0f96001cfdf58a43dfc91210bc6a"
  - "SHA512:cdff8dd0905f109b7d1110a418245505cf39a46c5450d3515a1f9468407368f1819dc8b031dd2bf56fed365397962c0e6ce02bd04c2ef88f66e8cd434451f016"
  - "SHA512:cf1928b8e63dde7cf099a3949006e9c24baeb52bb6cc2874cf14afd67ddb6d606583f29b71b4631ac2d2271b2932c2be687d80c627f79f4a6354cdfe5db3b078"
  - "SHA512:d15c9cad1d07b4857fdd1b22d2327eb6bb81b74a649dd2dadd33d6715b84c376c4887ac147d13bdbcb051dcf9816418355879bb5d4fae22199bc8551af763424"
  - "SHA512:d245fc6c8c1da2f869945f7ac086f0f6372e14113c281b40af94a4924b661af43ba42e28f496111f7ef5a845fa5ab2535b75eb06ef44e8a495b83d1926d43044"
  - "SHA512:d3346ba55fa9ff2c4f9fac431f858d9cb33284e4d7adcfde2ff90914e8f0c8851030944cb920a4bbd7039f632569839c728ffeb702c36e967c61a28094e325cf"
  - "SHA512:d78730e48c73ca14a876c92921d8cab52db374b0680f03365193be7f24cb55f0d01d8e1018c32fb67ebdb64b4a11af17b955e92b0c4af17184ab53bfb8528570"
  - "SHA512:d78ccfd3dcc18e979b765c3ce6efa145679a37195001d68abbaed023c711a94f2b79aa3a600c986ca194d23f6898a5e279f4af3ab94c7853e896a4aaef3d3927"
  - "SHA512:dab5017837abd7f9767dfaa857b85483254503103687d36bce61e9890dcacbf335c85f0544eb050fcad35f4e874f6fd9ac1c6cbf6c73fe8009175916c0287bf8"
  - "SHA512:dbd073086e4d40c1d8456646dda3fe88559cc7edffe3a567433b1cb1562759d3365cb17d2d24a31550194300cc0725f09ef0341107405eed76241c6b4fbf7059"
  - "SHA512:dcfbc53363d9037f5fd22caa093be66dd47ce450d6726e03fb32fe3b0f1cc9c74954efe52d003218a8e929501b0cfce53a24d98397dcc64121bf89f9dbf87438"
  - "SHA512:dd38f99ee7a13a8d14d55ef7c22218d0b109d739c112c789ac2faf1c2b5b652a736703e6eff7484287efeb8e338004daa42e7bdcd05a59c0768c1dbdd59fa9de"
  - "SHA512:df4d13824d25560aa049ca7d268523a4fe0976afbac22f2bb2f3bfc8e0258ab80baaa1c35a300c9ff67da2dedd39dd2b660a3d624db2c32e002446fb11f26147"
  - "SHA512:dfaf41c704b9d1a1880244fb51f025b41af18cd81df4a3e35de77c5fce64e15f551079c17041d3a002a5e069bbe53ee6baf1501f73ab85abc66917565a177abc"
  - "SHA512:e5f67e8cc46ffd96c6e523359a59e7e7ec2b7dd5b7a896bb218a313b9682ba19c2c97ac09286016d7a6472b84175c848aac08e3d7d3c09f4b23ae440ee5b51a3"
  - "SHA512:e6a04e12d9af2817dabd2d11eb363e5748f2a4861d876d33f2326c6558a4dd9f7883c0d5efffc9038a4db8605f8384d1c1e081cf6765da007112c0def491385e"
  - "SHA512:e714358a0abefa1109200200f59cbabe0d3c18eaa0f2d2b0f43fc4c2e48e1598a0c291becb034dc59701b1875d19af1a0d1ca6eba9b3638aa7db495318db4dc1"
  - "SHA512:e884414a4ca276f50d4a40b4cc1d63ab95e2ca982c344b62f4d73ac3b903c68aef0b1f1827acb258482844f0122721d48b5610c06c730608ca07029b0a94520d"
  - "SHA512:e88937a722a332766e9adca0945134ffc8214c48d56fa95e0eea3b671fc3c83df18f3bd748f46e49e8a01f88a5b42c837452d87ea6697f7953071db273ce5fd9"
  - "SHA512:eac2f77af5aa0d102f4c6f3cf152785c0d548c78c4a4e9272b4a77798e6590a1f23c30a05b03c8985662ee99d4bb21ddc10fc74c1f80ac4150bc45c4f7548246"
  - "SHA512:edf35680f4b5e90c1f1d7cbf774e98aa2695a405656e459a8f6e7a70097f58a3d65abb9e541c3f94cbdac00eb1de11b6a61bb56f012902a710397375dc10b1af"
  - "SHA512:f07c1f0fb27d3aa8d2fa1ee5775e15755cadd5fa5a8d0bfb80e42981ed55c3e7f0b8814f0424a61453473d2a64f8d044abff0b384889d13445f0777826161b6d"
  - "SHA512:f293bc39209a95655ae34e2449c85f4d58e5391a6590a57acf08ba7b4455da29323c5bdb885c9db919dac244593cc8854469bd7f10868438f6e998226fb0a81b"
  - "SHA512:f67c0f4b144b5ce3277038abe8c083e8cb681a3320e2e01bdd6a7a9b30cedf824ee2b1ac8450174167b597c969784e96d47de97c911fb5682384265011441559"
  - "SHA512:fa0cbd8b7044ce5a2cad2520424a7fca0fec78b1f0356ec8fa40861626cbae584ce73f268492d550a5e3e7ed47b65ac50add208cca0e75360db55c7a0086c8d8"
jenkins_master_views:
  - name: kamailio57
    regex: kamailio57.*
  - name: kamailio58
    regex: kamailio58.*
  - name: kamailio60
    regex: kamailio60.*
  - name: kamailio61
    regex: kamailio61.*
  - name: kamailiodev
    regex: kamailiodev.*
  - name: kamcli
    regex: kamcli.*
  - name: rtpengine
    regex: rtpengine.*
jenkins_master_views_default: kamailiodev
