---
jenkins_slave_ssh_pub: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCaD/xsMN3h1f8momph4PfPAJV4L2DBe9uXj3KolRLgJutVW77ZZNzNHFH12oXAa2gpytjLFIxxWtm0/NrQvCDe4ym+0ceDxcEiGJKyNknGz9j6rUvCbV5UZ40XabIaCLAqYgiU2OzlA+KIJ7ktP/ul5pKk/uEIfPF6dFHUd1pAPkRmcadiHYw6rTYmp4wAXe60QQDwecQWmOMKaFNjvV3jSd5MGl73Ojr1tZjbi0iZ/ayjpfl21sIK50KEu0FUl2rd32c/p52p2omW4zUJa/mvRcfGTTtA/KmAwfrx0zTfK1C7gdSfvQzGhUhG/U/1F/HY7t3aYy79X3KMq4EROB2vF9NFqDELlMOcIKrCdImHiqXidPhGaOstjM2RdCAzPOxmJ4utdHgoWiPGhHyUkMt/1KZc1u/lA3Xv1F9VPqWDVb2t1q+kFrgcrL3gNBSD4yjpfhpd6ZH94+LpljicjXcQAzHQFraaF8IOnI4eXAXPxe8s9xljAigjWaqKTZnj5LR13x83Yc7U9KJ4ztuwc7a9euy0btwpMgniEZCZasXlHAbJpFXIKnemnWxPzGotOvz1KCJ6RzYvaS2K9XVvuixRpd1pW8O9+l6VKTYJcv+MByZaia5MyVJvid6ZIFXSbkegFKMOQFxKFLx239iM9UZbSheN34fCRIDwO5/7mUC0OQ==
jenkins_slave_distris:
  - bionic
  - bookworm
  - bullseye
  - focal
  - jammy
  - noble
  - trixie
  - trusty
  - xenial
