---
jenkins_master_admin_address: "<jenkins@kamailio.org>"
jenkins_master_smtp_port: 587
jenkins_master_smtp_reply_address: no-reply@jenkins.kamailio.org
jenkins_master_smtp_tls: true
jenkins_master_executors: 5
jenkins_master_plugins_extra:
  - name: workflow-aggregator
  - name: git
  - name: copyartifact
  - name: parameterized-trigger
  - name: build-name-setter
  - name: email-ext
  - name: timestamper
jenkins_master_environment: production
jenkins_master_ec2_region: eu-central-1
jenkins_master_ec2_ami:
  - architecture: amd64
    type: t3.large
    id: ami-0b31c2adc9e7be95c
  - architecture: arm64
    type: m6g.large
    id: ami-0cc545d8a6da84f78
jenkins_master_ec2_name: "ec2-{{ jenkins_master_environment }}"
jenkins_master_ec2_security_group: jenkins_slave_production
jenkins_master_ec2_subnet_id: subnet-01610fec8f69c035d
jenkins_master_ec2_ami_distributions: "{{ ec2_ami_distributions }}"
## This configs depends on jenkins-jobs repository values
jenkins_master_scriptapproval_approvedscripthashes:
  - "SHA512:019e599257c1aa209d76ac0430e43a4769e34c85060405c13d68d8e0de97e327792a2099ac8d13716e26ab59bed5dca930e55f4876ea7e403f08b928ac20dbe4"
  - "SHA512:01feb18ce0553bcf7ed29e89d6849208ea9557f981dcfa8ecc2d0e660e386b5fe3741f22f444aa782a5ec604e36ea3a6c7536de84f1da76b5cc7aeb5db69f3c0"
  - "SHA512:05979d829b91c8aec12e13269f253489fcffde939b3426c72a983708c7fe32bf30d7f63779e593c90191a07be043d3f87cb8abe1d3a27440691ca0933978751c"
  - "SHA512:061d1e8d0effb46d05d7f424f5bf885c4dc7cc8b26a8dd73531eab23e9a6808e531ca5966a5af5a989bceb1285e80124347b2914516cf5a8e0b1c498de46861c"
  - "SHA512:06e60f14c5d73d93dabc88673265c9ea684afec930b28047b6c3f76e06b2a8916d3390b68ed5e80b0dfc1285b9efd34ff8a3925bd9dd1e35616c6668af70409c"
  - "SHA512:0748b9283d0015d8a6e838fcad5d60dbb178f3136e5de236c4f763b1d7d9b913cb6691ba2fcf2fc3ca379af126cbbd55e3048e50c827736f0beb4b217ff123b3"
  - "SHA512:07d73b8e0d90323aae658b6f8e74d2c1f35bc6c7b1412e2199bd812b09a30921e4bf762868134c27c11057e8ad111171e914a25730df8c277b9c2b7824e32177"
  - "SHA512:0b07d5e353f3e936bdd6e0aa23898af7fff6ecfa990e68b960166973c38ac57ae236aca5075a7844470cae8ae14cc2da54fa91edbf7b293bd3532e74a3537940"
  - "SHA512:0c0dab9c35cb2b40e5ad432ba1ea0e6e24cd3f64812cda14b2d77137ee3f7d4dd52332cc55646636063a03deff1999ae570f115a0ba7f7e7c7b41eaf81ea8cd3"
  - "SHA512:1027a8fc1dd1c5d8d30d3c3843dd5b1a37566b38156d3aaa8ef383497b2bfa77505f5a3fd2f32605fdcf9b7750372fc9300b6a5d697b4a825e3d0eda6a32ef7b"
  - "SHA512:16c88783b18a6d77688a5e2368d114ae0547ee3cee879f47f75d87a130eb64a068ccf879ec8f3cfd92f736f890430327c89eab8c126321e445f797dc0e55df77"
  - "SHA512:19211d2b1faf4c809d683cf85be66474836df32218e93623c2ddb2cc6b77ce98c6b2636ddca62731a9255a26f258b3592e44c61d07c2daa81efa4e662365272e"
  - "SHA512:1eb55329a166f2d027554ee6cfe53a98628ed181f9f36f7f66c07f0173a26534e20b078141a0cd47f5ce1c02bf2fc55999e27bace2b4755eebe1a9476e99b2bb"
  - "SHA512:1f9219881914b64f40341095aec5bcd1016c6e34fac0102d3857a3a4b4c2772e94274baa08418fdd859ff637331971e97aa076a1d5390a75dfe3c83921a29840"
  - "SHA512:26dcd1b40ee91c8b7760386c0d5737439f03e2367196cf6748fd346475343fcb3c341503dc0e3c2ec9a20a08ab106d0df004dc9a34c0ce316465b142e713ad78"
  - "SHA512:277ea1c362fed718b1e5ddd0934c4cf105c4c43b27ff89e0f8ecb14819c9d96d8e1212637d7e22704646d2e22953118466adf78c9f163bc33f29381e903d9a43"
  - "SHA512:2c6d041c36e55e27f2ce230df4d52952bf1bed5e64efc930cd054bc90ec56df474f1a458c408b8666be1f8045bc0344050916239d0aa2b6025d920da4e25928a"
  - "SHA512:2dcf106d1f6c3aac6950e6d48b9850eb78e0879cea21ec54c12c74bff6838b31696089d98c3545768e62fe9555508217dc3cd3e6a4012617a3d8bbe7dab300bf"
  - "SHA512:2efb3fea122072e934239c879044c9bc080a509562a4c66066ffb69d681f0e8455eedeb84ea1f3ec51dce0e6e67ad3e6c66f27452dedb48cd857e8a439473103"
  - "SHA512:30440910cdfa23e66854d2b6fb27de4537f264458f81d0de086c16ff96f81e4032b16a66155bb2bcfa0d708aff5450b140ee946d70326aa1fc11e8c7444e3ba9"
  - "SHA512:3200e65cd3487625e2c2227d2f0f9dd81673a03015f05fcded12dcacd199f64067a9225a40d4d40a2d7b94255bf9120fee3356553b1fcdaf327b91b9ab2c393b"
  - "SHA512:3355d768df72804f35054610bbd208b61d673311aee2a8f03c0770570159dc6b7acfcc5ee43b3f2254e116110d5c59c9b11636d4340d4c81a97d577839222b54"
  - "SHA512:361358134528809a5d257e60cfb9adbce918e412e47babc1774f692ebb06bbdd39e2cccd7c4808d3a1c096ee4e3034e39b82fd5f3c53f3d0a9bb67a8a4271a3d"
  - "SHA512:39c30f2917194f2980bdd6dedd2eabd07773a3a5bc944a8838cc3c5465e7cdfbb0229a3bd901a7217c0fc5c7531cc6ea01432588aa1ef82cd36e9464981533f9"
  - "SHA512:3a3c1bb2f52c0d224e9b38844a9f605686fe4159148e067755f2458054fcb44f59a0f73b10fd6d14334228ea0469845a9c406185941174b5682efaf236a8c20b"
  - "SHA512:3e297db266ac66174a8123992ecd9039171626ca928db9a6acea97189a7875ac45a8ee9b1ab93f4a50ca12d1560f5304049a7a488cd2d387a6c7894361a8e418"
  - "SHA512:3e921a69697d99bece09092f9f5b28b4cdf1df3d6dc14686c6b0da465796a8a1a8e8637973567fa1b70b8840ad88e8275b2a596cf97c6a5ea15753c37236c567"
  - "SHA512:4091710e98aae857f37e4ff22c19af0229181f0d6687853e56445fb85eecfabb668e00b9f47f7e36438880ed3aa161d851c7fce0a791326a9152505bd59e1bdf"
  - "SHA512:43474fb64ce3caee795115c79d8bd202663b316e90d816d13b88de6b4e0adb519f91157de0587cadf6a78b74fbcb272d4943fa05f4f5943efe7c3d9dd389d2dc"
  - "SHA512:469fa1b026e7ecab74cc6e8b7c9265bad4c92884e7131bfc3b872b41cd921c61f2ad4048156687696345d0192be652c2f95e55564424c0c521e7532381010d1d"
  - "SHA512:479441eca613702b4bd63afbb4fd1e1515ee897a39177a540f6bdbeb419d7e6b229b9cf836f76062b0e80157fbce3a75f9f11cdda3983a328a64309e5d5fe0b9"
  - "SHA512:4946a9d069380bc5fcd30fafa772793aad1319bd6ef1f20ae456ecc61caafec754bd2fd7384dfdf8b2169f92a7c2abba1d40d4155f72c32939a06418202b4c85"
  - "SHA512:54ebe19563fb7fcfb496ef4e9d4efee124b0c8400b4bea97ef18fdbaf3855577651cdb289ffe5cc1a041a6af641e5449c360dbbd33166764d5e817aeb04261ff"
  - "SHA512:5b5d611de5ec649ab883e405a45413d3952239f949ccd0717ce29d23d248a605e89db5d1662da285f04423fb8bed3d9bee71640d7c578352edb43bd29b02117a"
  - "SHA512:5f1542be4c2cf999586b8620c97a5aa4d8871f39bf5af157966cf93afe8fb5a63f7ed26b29097e19b17de5d0baa772bfca5bb6eee70c0aed55f3ee42a876dee3"
  - "SHA512:6e1b725ae58a837a081f1c376f3196a73ef258377cbdbb69976b3788e1dc81a4e9a8520c46e1c44b58c96cbfcf8913c62821af781f83aff2655708b44b236f49"
  - "SHA512:72f4c6f9f57dfa7de65b0b730943259c7770b4f1a2aece2db515a8448db9f19ae271d6cfc548ef7c93c083e03222ee682c0aa7a482ae3a05eb3d640222b2ba5d"
  - "SHA512:7557b945cf61734b3ad45bb668171c3ff9fa78843ea6b87459d24908ea53bebce12e4372e5880e2e4a8918f001b256a86d735a39db0e171e6ecde19f41851b46"
  - "SHA512:781f4c93e07de60de8cdb8e2c97c2a5abbf386b94bbafa88472ea884595c5d920f75b03cf6c31c4ec32d43e1c133fcd9799f9efcd3ed0475238013e2f98a1692"
  - "SHA512:7a3d8d2798de36b61ff8c7925233d5d52f67ee5de0430e0a4c3218dc8a8b740dd482f9ef9d49493189acc75552293cbcdd223e4a611f6d5777d4c622aa98c176"
  - "SHA512:7ae5af89d03070af152314e532e5e32935d9fd02a009ef9e58674caa523feb0c87a1d6ba527f26fe3cb1e53b9d43eb44809f2e230cf21b5bf92a8d6da4c1f350"
  - "SHA512:7c8178535daf35ebd0fee31c337f8e5d0ed48ca0c034f0faa139eb2a7456ea95d25269eb0f419eb9a7954bbf89c17a248b71cb9ec4462bfe8afbac5328abb4a5"
  - "SHA512:7f198a0a6b6c57bae74481076c910d9f63293960b3fcf7f9f18a72974884dda8175d88c7461b307c9cea3f37b33151dae57eed9fcf78ae43f99a69a7c53fcd29"
  - "SHA512:80a6932bd96d454d491f4dcb34301f5357fb9f10e90ab9e5838e12c01902c76a337757fd84bdcebd8bb96b5ab5832d1ef0c3e0cb1fa95bf0c46da4e47a650d83"
  - "SHA512:892e773d3e9d68ad1e407de040c0d3f2d9a1b1f5c3710b6230cfef2a8dc20da5554bb5d96afd3532b403b76d41a4e86d9a0bf452cec36a4ce429f5305f8bf8bd"
  - "SHA512:8b65f414af908b3a57f5c23919596b6a0ac50b0a3e181ea658dc66c8dab9891867b8d3729447f0b5c08d41a0e8bd8ad20b670f64733745c6471e79bef2d31a6c"
  - "SHA512:8c5d77a967acee06dc63ceed95433903c3a2b41c74e1bbca2637df570095266f51fefb27330083b4adfef5205a58f0212ca335c8724c4e26c86e71f261f46e33"
  - "SHA512:8c6bd4ec4f0b887cde265bd30003fae1843e89f4e795fba57be45154f2fb6638555866de0246b5e3b2989e32b52f42260dab8f37594d30901b69495899f124d5"
  - "SHA512:94acd5d867b17e2ab02e3f39c9fae1ef128c9aa53e8c47ff8bb430bf41e13ce7314059132dc1efd3cb15e92c2b3c8121b4423f3c7f5a2cef90607fd9760a8a56"
  - "SHA512:94bb827ece63b4fffbaafdd72a1514360b32c40ced32b57fcd275756c2837edba9b4f9328f9196fc20b73c3686ccdcaa1666234104ff10d2ea076d6ad79a96a5"
  - "SHA512:9892887d343a7c8c787778a957ca4861c747f62c782bcdef16babc7a6d7fc9cba4de576ee0943173153f9d74ef4b90ea755a53a8a1a749c14205643e0a5be6f2"
  - "SHA512:9f82648b6e9bedce1475defa210a2f7f52f132e6118834b90c9233bb410c43d0c2f6d09c6269cd907baca7b8f0d4d852d98d03c2f56febb39bbe586bf242ce35"
  - "SHA512:a3ccf6b6fa33ad4ac916e7a48d6e344753b32dbed2e8c11dae624e1935231f0bbfda7130926e201ae047bae523cd0de619f242fd19e908d4e31cccdb34a88108"
  - "SHA512:a7271db6207b0a5f97891b93682214520dbaf16ae4510fe4e902fc74bf19c7fcdb2974d6a921b7963ca8eafe5ed597e7d159875956b3712bfcec203c0034928f"
  - "SHA512:a885e669afc0d1f1b403f03ebae79e20f81469edccd4871dd77f592218bc3e793cd0be30cee8e39f4f73228dcce01fe56a4dfe5599073913da32a2505d9cccd0"
  - "SHA512:ad9a40096563c9249a3006a22b4acf1160e5a7b2c36d928bc44fe19e87f888506e286d72c98eb44f3bc9507352fb2bdeedb3fce5ec117f11cc1bc7fde264f40e"
  - "SHA512:b104954cc8a027575fd3e4eed5f74fb361a32a4c16582a244fb3a41167a0856f601010fd38d36bc6242e25ed8bec424ea2f726756ebb1ee2981c47133a19062b"
  - "SHA512:b16a1049d8efaa3f523214e6dabf9016383b30672efebe784feb07c7d7eec92de5bd86d1e9de50e8a2d6393e6ef608465b83b86008ad00ce8c7d4bc741f4572a"
  - "SHA512:b3513a8a56bd103687cd90e70530518e079188fe794d91eef348f57433abe0374b1bc498ea9403d4d471c561bb9493e47ef3375c6e34d579400c97a537598186"
  - "SHA512:b46de7ee482b5860cbe20c795251d5fe0eee8656abbc4c62971f542ae8bad884ba6508bf0472341056b2ab1637d4bc20dc78ab587f62233754f4941eb173dcbb"
  - "SHA512:b6a3891ee218747826b30d0b988665f57df770bc2d8c33a1999a3538e9832df3179368efb67469b3890cfc0d7a3be93100a8d8689f1d51a4c41791d9710a30fa"
  - "SHA512:c002d1723b2e90501c9671718f297395519eb77fcdcad9243de98929afcbc0d42a44de4282eb3b15eb808b18567646b8037f60d176e3fe4a4e62dcb6fa68c715"
  - "SHA512:c0167632abc33fa9c73cb4b383faad25828b72d157f62019a6701e9f41579ce7f4c2e43af480fc2d12bfed7651ce082126c3e5d70c34f9617411fde28d5f3d79"
  - "SHA512:c3aa51296f7e82467ccb8dbb354630def8b37df1e0ec44591eb64c6aabb3f362c15722d90b14def685df3cfadbe4cdd60828dc82324ce139385b2213ca748859"
  - "SHA512:c848d25b44c0f6c5a66a89b1e07338774a00dea311a90d15a2f2615017cef1260d1bae2046b0c318559f2bdf5a7f223234aa10f77a467e61e06908353f3e39bd"
  - "SHA512:c8dce8ffef6134da1da8dc592738b44885a1c451c21f6bd244ce03108ed1b05cfb1721a7e4f52e551130e7ffcaa69c7bd54134887a39261d5858ec10313def29"
  - "SHA512:cd5c84729cbb7f90715d1f16a51d7238386afbcd6e5b9d254fa17598749186d3f255fdc06b5c1d36f44871fef77240c3e620cec7b552f571231435090bc3b707"
  - "SHA512:d0cb694c568fc524e210c65a805092fb232dd40b24af726ec016aa01e85a8b6f548722d31455c0e3e203240ec4ea9d19c969d6fe2149f50dc80d1179db2d8d6a"
  - "SHA512:d15b40b38ac67e595bb7fa2cf77c61149f5cd80abbfb11602cd34b6017738486397dbe71b7d7e903e850534da3737e9cbdfce061fee653fa85fb01a6cd27c632"
  - "SHA512:d79440a4162c0bedef204b3b40b2ad1685dbc5ae9509e50360fd911cee6ae6ba13b23f193cbab791f38f45cb2e15530c5eb4122645cecd86add5290bb99a19f2"
  - "SHA512:d7c76cf5240b90b448a9591bcf1a493f15b1fb11a0af686bd2497dfaad4fa96da90925c6118d9801786d39b38870f82082b2b41023fe99da0950137e9de1f341"
  - "SHA512:d8a94abd83784e46ae1267919c80df71538378418bc3b1463d7f69dce64255016bfa71596994f2dcfeb5d3c1a49aef5aea44f736f8d833f6eed3486d5d14582b"
  - "SHA512:d9b1da38aef7289fb23a0df1e4fa37e620d66b6df3bb82d678c084fd5534fe8d8fb3f6d500c09af9fe5fa97950495bf5277eef228274e33dab59aa5f373e3720"
  - "SHA512:db3c067bc0a472a50e80ddd13410b298d7f310aa0b7b2cddbb77b28ed85086b08a3cf638063563d655ba3996f6abd13b4256ee1e7f013c263021d5d09389879d"
  - "SHA512:dc40e3c262d74883de95a90600ff8737b986602501602f1dd6ecc53c540ae72b49aa8e844a0e6f2bfbe0de01bc9a1a3a5d358acea38cb3b9512f54392bd814b0"
  - "SHA512:dd3685b148aa90eaba973850b78aca56d12849e69e3a0c2c72b0da91e4f33d4202129ffdcfb488fedd83c80e1e41d99e3a94adbcf2ff46d8b5886577431bfb0a"
  - "SHA512:de024645811d05daacc945732583e6386af139ec29ca37a9d242a7abc02a04c7d2db85c6a910303314146ad7a5b571a738cd185ed68f65657e9f210016279e69"
  - "SHA512:de4b86dd74ca5e5df5a9100b2bd466c685a0551b9e4ddff700076b649d495df420e5093d41c8ad5667ee2375d0fc1982572bf5e6dda942c4d309b48a9129a775"
  - "SHA512:de89ade9d01be38a3620de5dcb60d5e2d025c0ed6234200a1fbff218e0cc8e3cb02fc2adc37845601fb84ad6b4f1b3477549bbabf733c6eb7e5b9dbd0046ca57"
  - "SHA512:e2a9eb8475715650554e65d68bdc575701bd4d74fad14fe9a8bc7a84c7c7bc1684669baeea383746a20bf94f77ebb428f4d8466d6c7ae3b4584911cb0a13529b"
  - "SHA512:e5637e4e87ffa2d8f49c7d44a914ba20d74d83ebd55784b6b6ad9a060ae116112db819a281f07ed11a810fd48bc617aeade9db1291de912e4447fcac0df4b57b"
  - "SHA512:e6417ae83ad527e21aca5db1ca9647cbaa4348f5fb5f5648f2953498d596ce68e7552ba6d81e938c05d1332295ea7cdd71cf32a0283f5ed24c4162a5c4e376f3"
  - "SHA512:e74f9d67d5b6048ad2f675ce409ba195812556120c69592e5d05d93ab10d1d0e55a65b959a535966e570cc2141313cf9c6bfa386fd6f606ffadb702729bc0f67"
  - "SHA512:ebf080756f2a88fe21f58aaec35fb8db413aa10f17ecf9d23cb57c4e7212d1bd50d1dc3b3ec4033560815d889711ad99486cbb7f8a78c161a2312354e3d43a94"
  - "SHA512:ed182a057504eb2213b1e669e47a24d62e115f57ca8905a28c6d2f1226e38ec6bfc9ebe580b18b9b05d8f44e6cf83c673029716aac1bf14fe8824f04ce373c58"
  - "SHA512:eee123036b1c5c105ed08502885767ee0f8961c60eb4d77fe1b0fe64cb21aa12ff234668317deec35fa278ab06d9859fbb77cc201068c8096fa27087e3d56a6b"
  - "SHA512:f0586759445625df44efca2c2b5f7810fe2656ab4a2d7d3d1e6b8e99262161e7283d8723dcf5e0c9c86f33dd5117cbc3f18869b4938cc1ce8bbd9d213b80b1c3"
  - "SHA512:f5a8c9fb4cece1f7acde983bac4b8d9a78402fd45f376d2407c4ff740e6b0a36234b507c7314a04e1f53e967ccb0131760bd802f99676fa7e32b3a9652deb059"
  - "SHA512:fd8581a92d9a3be90b4b80ddc392952c74f77716b117cd1340b83d46005e236bc4c11adeaacf79a2255407af32a91553235babbbd090d5be2b4109c0d1343dbf"
  - "SHA512:fe09963efc8118febb411ec4cd852ba51c9fa7f0b30d2b9a14d8b9a1a06de8521789a9cfcbde7d06d43bab94f4a1961eada95dcd6eccb634cce08e231d8482ad"
jenkins_master_views:
  - name: kamailio57
    regex: kamailio57.*
  - name: kamailio58
    regex: kamailio58.*
  - name: kamailio60
    regex: kamailio60.*
  - name: kamailiodev
    regex: kamailiodev.*
  - name: kamcli
    regex: kamcli.*
  - name: rtpengine
    regex: rtpengine.*
jenkins_master_views_default: kamailiodev
