---
- name: reload_nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true

- name: restart_apt_cacher
  ansible.builtin.service:
    name: apt-cacher-ng
    state: restarted
  become: true
